// Additional 25 projects to be added to projects-data.ts
export const additionalProjects = [
  {
    slug: 'social-media-analytics-advanced',
    title: 'Advanced Social Media Analytics Dashboard',
    shortDescription: 'Comprehensive analytics platform for tracking social media metrics and engagement',
    fullDescription: 'Build a powerful social media analytics platform that aggregates data from multiple platforms (Twitter, Instagram, Facebook, LinkedIn), provides sentiment analysis, tracks engagement metrics, identifies trends, and generates automated reports with actionable insights.',
    domain: 'DATA_SCIENCE',
    difficulty: 'INTERMEDIATE',
    estimatedDuration: '6-8 weeks',
    recommendedYear: 'Third Year',
    primaryTechnology: 'Python',
    techStack: { frontend: ['React'], backend: ['Python', 'Django'], database: ['PostgreSQL', 'Redis'], tools: ['Celery', 'Plotly', 'Twitter API', 'Facebook Graph API'] },
    architecture: 'Django backend, React frontend, PostgreSQL for data, Celery for async tasks, Redis caching, multiple social media APIs',
    features: ['Multi-platform integration', 'Sentiment analysis', 'Engagement tracking', 'Trend identification', 'Competitor analysis', 'Automated reports', 'Custom dashboards', 'Influencer detection', 'Hashtag analytics', 'Export functionality'],
    skillsRequired: ['Python & Django', 'Data analysis', 'API integration', 'Data visualization', 'Social media platforms', 'NLP basics'],
    learningOutcomes: ['Integrate social APIs', 'Implement sentiment analysis', 'Build data pipelines', 'Create interactive dashboards', 'Handle rate limiting', 'Design analytics systems'],
    timeline: [
      { week: 1, title: 'Setup', description: 'Django setup and API credentials' },
      { week: 2, title: 'API Integration', description: 'Connect social media APIs' },
      { week: 3, title: 'Data Collection', description: 'Build data collection pipeline' },
      { week: 4, title: 'Sentiment Analysis', description: 'Implement NLP sentiment' },
      { week: 5, title: 'Dashboard', description: 'Create React dashboard' },
      { week: 6, title: 'Reports', description: 'Automated reporting system' }
    ]
  },
  {
    slug: 'online-exam-proctoring-advanced',
    title: 'Advanced AI-Based Online Exam Proctoring System',
    shortDescription: 'Automated exam monitoring with face detection, eye tracking, and anomaly detection',
    fullDescription: 'Develop an AI-powered online examination platform with automated proctoring capabilities including face detection, eye tracking, tab switching detection, multiple person detection, and audio monitoring. Features secure browser mode, question randomization, and detailed violation reports.',
    domain: 'MACHINE_LEARNING',
    difficulty: 'ADVANCED',
    estimatedDuration: '8-10 weeks',
    recommendedYear: 'Final Year',
    primaryTechnology: 'Python',
    techStack: { frontend: ['React', 'WebRTC'], backend: ['Python', 'TensorFlow', 'OpenCV', 'FastAPI'], database: ['PostgreSQL', 'Redis'], tools: ['AWS S3'] },
    architecture: 'FastAPI backend, TensorFlow/OpenCV for CV, React frontend with WebRTC, PostgreSQL for data, Redis for sessions, AWS S3 for recordings',
    features: ['Face detection', 'Eye tracking', 'Tab monitoring', 'Audio analysis', 'Screen recording', 'Question bank', 'Auto-grading', 'Violation alerts', 'Secure browser', 'Detailed reports'],
    skillsRequired: ['Computer vision', 'Deep learning', 'WebRTC', 'Python ML stack', 'Security concepts', 'Real-time systems'],
    learningOutcomes: ['Implement computer vision', 'Build real-time monitoring', 'Handle video streams', 'Design secure systems', 'Deploy ML models', 'Create exam platforms'],
    timeline: [
      { week: 1, title: 'Setup', description: 'Project setup and model selection' },
      { week: 2, title: 'Face Detection', description: 'Implement face recognition' },
      { week: 3, title: 'Eye Tracking', description: 'Gaze detection system' },
      { week: 4, title: 'Tab Monitoring', description: 'Browser activity tracking' },
      { week: 5, title: 'Audio Analysis', description: 'Voice detection' },
      { week: 6, title: 'Exam System', description: 'Question bank and delivery' },
      { week: 7, title: 'Reporting', description: 'Violation reports' },
      { week: 8, title: 'Testing', description: 'End-to-end testing' }
    ]
  },
  {
  slug: 'smart-ecommerce-recommendation',
  title: 'AI-Powered E-commerce Recommendation System',
  shortDescription: 'Personalized product recommendation engine for online stores',
  fullDescription: 'Build an intelligent recommendation engine that analyzes user behavior, purchase history, and browsing patterns to suggest relevant products in real-time.',
  domain: 'DATA_SCIENCE',
  difficulty: 'INTERMEDIATE',
  estimatedDuration: '6-8 weeks',
  recommendedYear: 'Third Year',
  primaryTechnology: 'Python',
  techStack: { frontend: ['React'], backend: ['Python', 'FastAPI'], database: ['PostgreSQL'], tools: ['Scikit-learn', 'Pandas'] },
  architecture: 'FastAPI backend for recommendation engine, React frontend, PostgreSQL for user data',
  features: ['User behavior tracking', 'Collaborative filtering', 'Product similarity engine', 'Real-time suggestions', 'Analytics dashboard'],
  skillsRequired: ['Machine learning basics', 'Data preprocessing', 'REST API development'],
  learningOutcomes: ['Implement recommendation systems', 'Build ML APIs', 'Handle user analytics'],
  timeline: [
    { week: 1, title: 'Data Collection', description: 'Collect user activity data' },
    { week: 2, title: 'Model Building', description: 'Collaborative filtering implementation' },
    { week: 3, title: 'API Development', description: 'Deploy recommendation API' },
    { week: 4, title: 'Frontend Integration', description: 'Display recommendations' },
    { week: 5, title: 'Testing', description: 'Model evaluation and optimization' }
  ]
},
{
  slug: 'inventory-management-enterprise',
  title: 'Enterprise Inventory Management System',
  shortDescription: 'Advanced inventory tracking system with supplier integration',
  fullDescription: 'Develop a scalable inventory management system supporting stock tracking, supplier management, purchase orders, low-stock alerts, and reporting.',
  domain: 'WEB_DEVELOPMENT',
  difficulty: 'INTERMEDIATE',
  estimatedDuration: '8-10 weeks',
  recommendedYear: 'Third Year',
  primaryTechnology: 'Java',
  techStack: { frontend: ['Angular'], backend: ['Java', 'Spring Boot'], database: ['MySQL'], tools: ['Docker'] },
  architecture: 'Spring Boot backend, Angular frontend, MySQL relational database',
  features: ['Stock tracking', 'Supplier management', 'Purchase orders', 'Low stock alerts', 'Analytics reports'],
  skillsRequired: ['Spring Boot', 'Database design', 'Enterprise workflows'],
  learningOutcomes: ['Build enterprise systems', 'Design relational schemas', 'Implement role-based systems'],
  timeline: [
    { week: 1, title: 'Planning', description: 'Database schema design' },
    { week: 2, title: 'Stock Module', description: 'Inventory CRUD operations' },
    { week: 3, title: 'Supplier Module', description: 'Supplier management system' },
    { week: 4, title: 'Reports', description: 'Analytics dashboard' },
    { week: 5, title: 'Testing', description: 'System integration testing' }
  ]
},
{
  slug: 'ride-sharing-platform',
  title: 'Ride Sharing & Carpooling Platform',
  shortDescription: 'Uber-like ride sharing application with real-time tracking',
  fullDescription: 'Build a ride sharing application that connects drivers and riders with real-time GPS tracking, booking system, fare calculation, and rating system.',
  domain: 'MOBILE_DEVELOPMENT',
  difficulty: 'ADVANCED',
  estimatedDuration: '10-12 weeks',
  recommendedYear: 'Final Year',
  primaryTechnology: 'React Native',
  techStack: { frontend: ['React Native'], backend: ['Node.js'], database: ['MongoDB'], tools: ['Google Maps API', 'Socket.io'] },
  architecture: 'React Native mobile apps, Node.js backend, MongoDB storage, real-time tracking via Socket.io',
  features: ['Ride booking', 'GPS tracking', 'Fare calculation', 'Driver rating system', 'Payment integration'],
  skillsRequired: ['Mobile development', 'Real-time systems', 'Geolocation APIs'],
  learningOutcomes: ['Build scalable mobile apps', 'Implement real-time tracking', 'Handle location services'],
  timeline: [
    { week: 1, title: 'System Design', description: 'Architecture planning' },
    { week: 2, title: 'User System', description: 'Driver and rider auth' },
    { week: 3, title: 'Booking Module', description: 'Ride request system' },
    { week: 4, title: 'Tracking', description: 'Live GPS updates' },
    { week: 5, title: 'Payments', description: 'Online payment integration' }
  ]
},
{
  slug: 'cloud-file-storage-system',
  title: 'Cloud-Based File Storage & Sharing System',
  shortDescription: 'Secure file storage and sharing platform with access control',
  fullDescription: 'Develop a cloud file storage system where users can upload, share, and manage files with encryption and access control policies.',
  domain: 'CLOUD_COMPUTING',
  difficulty: 'INTERMEDIATE',
  estimatedDuration: '8-10 weeks',
  recommendedYear: 'Third Year',
  primaryTechnology: 'Node.js',
  techStack: { frontend: ['React'], backend: ['Node.js'], database: ['PostgreSQL'], tools: ['AWS S3', 'JWT'] },
  architecture: 'React frontend, Node.js backend, AWS S3 for storage, PostgreSQL metadata database',
  features: ['File upload', 'Access control', 'Encrypted storage', 'Shareable links', 'Admin dashboard'],
  skillsRequired: ['Cloud storage basics', 'Authentication', 'File handling'],
  learningOutcomes: ['Integrate cloud services', 'Design secure storage systems'],
  timeline: [
    { week: 1, title: 'Setup', description: 'Cloud configuration' },
    { week: 2, title: 'Upload Module', description: 'File handling implementation' },
    { week: 3, title: 'Access Control', description: 'Role-based permissions' },
    { week: 4, title: 'Sharing System', description: 'Public/private link generation' },
    { week: 5, title: 'Testing', description: 'Security testing' }
  ]
},
{
  slug: 'smart-attendance-system',
  title: 'Face Recognition Based Smart Attendance System',
  shortDescription: 'Automated attendance tracking using computer vision',
  fullDescription: 'Develop a smart attendance system that uses face recognition to mark attendance automatically and generate reports.',
  domain: 'MACHINE_LEARNING',
  difficulty: 'ADVANCED',
  estimatedDuration: '8-10 weeks',
  recommendedYear: 'Final Year',
  primaryTechnology: 'Python',
  techStack: { frontend: ['React'], backend: ['Python', 'FastAPI', 'OpenCV'], database: ['PostgreSQL'], tools: ['TensorFlow'] },
  architecture: 'FastAPI backend, TensorFlow face recognition model, React dashboard',
  features: ['Face recognition', 'Attendance logging', 'Report generation', 'Admin dashboard'],
  skillsRequired: ['Computer vision', 'Python ML stack', 'API development'],
  learningOutcomes: ['Build CV systems', 'Deploy ML models', 'Handle biometric data'],
  timeline: [
    { week: 1, title: 'Model Setup', description: 'Face recognition model training' },
    { week: 2, title: 'API Integration', description: 'Attendance API development' },
    { week: 3, title: 'Dashboard', description: 'Admin panel implementation' },
    { week: 4, title: 'Testing', description: 'System validation' }
  ]
},

{
  slug: 'real-time-collaboration-editor',
  title: 'Real-Time Collaborative Code Editor',
  shortDescription: 'Multi-user code editor with live collaboration and chat',
  fullDescription: 'Develop a collaborative code editor where multiple users can write and edit code simultaneously with real-time updates, chat functionality, and version history.',
  domain: 'WEB_DEVELOPMENT',
  difficulty: 'ADVANCED',
  estimatedDuration: '8-10 weeks',
  recommendedYear: 'Final Year',
  primaryTechnology: 'Node.js',
  techStack: { frontend: ['React'], backend: ['Node.js'], database: ['MongoDB'], tools: ['Socket.io', 'Monaco Editor'] },
  architecture: 'React frontend with Monaco editor, Node.js backend, WebSocket communication using Socket.io',
  features: ['Live editing', 'Chat system', 'Version control', 'Room-based collaboration', 'Syntax highlighting'],
  skillsRequired: ['WebSockets', 'Real-time systems', 'Frontend state management'],
  learningOutcomes: ['Build collaborative apps', 'Handle concurrent editing', 'Implement real-time sync'],
  timeline: [
    { week: 1, title: 'Setup', description: 'Project initialization' },
    { week: 2, title: 'Editor Integration', description: 'Integrate Monaco editor' },
    { week: 3, title: 'Real-time Sync', description: 'Implement WebSocket logic' },
    { week: 4, title: 'Chat & Versioning', description: 'Add chat and history' },
    { week: 5, title: 'Testing', description: 'Concurrency testing' }
  ]
},
{
  slug: 'smart-agriculture-iot',
  title: 'Smart Agriculture Monitoring System',
  shortDescription: 'IoT-based crop monitoring with soil and climate analysis',
  fullDescription: 'Build an IoT-based agriculture monitoring platform that collects soil moisture, temperature, and humidity data to optimize irrigation and improve crop yield.',
  domain: 'IOT',
  difficulty: 'INTERMEDIATE',
  estimatedDuration: '8-10 weeks',
  recommendedYear: 'Third Year',
  primaryTechnology: 'Python',
  techStack: { frontend: ['React'], backend: ['Python', 'FastAPI'], database: ['PostgreSQL'], tools: ['Raspberry Pi', 'MQTT'] },
  architecture: 'IoT sensors connected via MQTT, FastAPI backend, React dashboard for monitoring',
  features: ['Sensor data collection', 'Real-time monitoring', 'Automated irrigation alerts', 'Data visualization'],
  skillsRequired: ['IoT basics', 'MQTT protocol', 'Backend APIs'],
  learningOutcomes: ['Implement IoT systems', 'Handle sensor data', 'Design monitoring dashboards'],
  timeline: [
    { week: 1, title: 'Hardware Setup', description: 'Sensor configuration' },
    { week: 2, title: 'Data Pipeline', description: 'Backend integration' },
    { week: 3, title: 'Dashboard', description: 'Visualization system' },
    { week: 4, title: 'Automation', description: 'Alert system implementation' }
  ]
},
{
  slug: 'ai-chatbot-support-platform',
  title: 'AI Customer Support Chatbot Platform',
  shortDescription: 'AI-driven chatbot for automated customer service',
  fullDescription: 'Develop an intelligent chatbot system that handles customer queries, integrates NLP, and provides automated support for businesses.',
  domain: 'MACHINE_LEARNING',
  difficulty: 'INTERMEDIATE',
  estimatedDuration: '6-8 weeks',
  recommendedYear: 'Third Year',
  primaryTechnology: 'Python',
  techStack: { frontend: ['React'], backend: ['Python', 'FastAPI'], database: ['PostgreSQL'], tools: ['Transformers', 'NLTK'] },
  architecture: 'FastAPI backend with NLP model, React chat interface',
  features: ['Intent detection', 'Automated replies', 'Conversation history', 'Admin training panel'],
  skillsRequired: ['NLP basics', 'Python ML stack', 'REST APIs'],
  learningOutcomes: ['Build NLP models', 'Design conversational interfaces'],
  timeline: [
    { week: 1, title: 'Model Setup', description: 'Intent classification model' },
    { week: 2, title: 'Backend API', description: 'Chat API implementation' },
    { week: 3, title: 'Frontend', description: 'Chat UI design' },
    { week: 4, title: 'Testing', description: 'Conversation testing' }
  ]
},
{
  slug: 'event-management-platform',
  title: 'Event Management & Ticket Booking Platform',
  shortDescription: 'Platform for organizing events and selling tickets online',
  fullDescription: 'Build a complete event management platform allowing organizers to create events, manage registrations, and sell tickets securely.',
  domain: 'WEB_DEVELOPMENT',
  difficulty: 'INTERMEDIATE',
  estimatedDuration: '8-10 weeks',
  recommendedYear: 'Third Year',
  primaryTechnology: 'Node.js',
  techStack: { frontend: ['React'], backend: ['Node.js'], database: ['PostgreSQL'], tools: ['Stripe'] },
  architecture: 'React frontend, Node.js backend, PostgreSQL database',
  features: ['Event creation', 'Ticket booking', 'Payment integration', 'QR-based entry system'],
  skillsRequired: ['Payment integration', 'Database modeling'],
  learningOutcomes: ['Build booking systems', 'Implement secure payments'],
  timeline: [
    { week: 1, title: 'Schema Design', description: 'Event database modeling' },
    { week: 2, title: 'Booking Module', description: 'Ticket purchase system' },
    { week: 3, title: 'Payment Integration', description: 'Stripe implementation' },
    { week: 4, title: 'QR System', description: 'Entry validation system' }
  ]
},
{
  slug: 'online-marketplace-platform',
  title: 'Multi-Vendor Online Marketplace',
  shortDescription: 'E-commerce platform supporting multiple sellers',
  fullDescription: 'Develop an online marketplace where vendors can register, list products, manage inventory, and process customer orders.',
  domain: 'WEB_DEVELOPMENT',
  difficulty: 'ADVANCED',
  estimatedDuration: '10-12 weeks',
  recommendedYear: 'Final Year',
  primaryTechnology: 'Next.js',
  techStack: { frontend: ['Next.js'], backend: ['Node.js'], database: ['PostgreSQL'], tools: ['Stripe', 'Redis'] },
  architecture: 'Next.js frontend, Node.js backend, PostgreSQL relational database',
  features: ['Vendor dashboard', 'Product management', 'Order tracking', 'Payment system', 'Ratings and reviews'],
  skillsRequired: ['Full-stack development', 'Payment gateways', 'Role-based systems'],
  learningOutcomes: ['Design scalable e-commerce systems', 'Handle multi-tenant data'],
  timeline: [
    { week: 1, title: 'Planning', description: 'Database schema design' },
    { week: 2, title: 'Vendor Module', description: 'Seller registration system' },
    { week: 3, title: 'Product Module', description: 'Product listing feature' },
    { week: 4, title: 'Orders', description: 'Checkout and tracking system' },
    { week: 5, title: 'Testing', description: 'Load testing' }
  ]
},

{
  slug: 'task-automation-platform',
  title: 'Workflow & Task Automation Platform',
  shortDescription: 'Automation system for scheduling and managing recurring business tasks',
  fullDescription: 'Build a workflow automation platform that allows users to create automated task flows triggered by events such as emails, database updates, or API calls. Includes scheduling, notifications, and execution logs.',
  domain: 'WEB_DEVELOPMENT',
  difficulty: 'INTERMEDIATE',
  estimatedDuration: '8-10 weeks',
  recommendedYear: 'Third Year',
  primaryTechnology: 'Node.js',
  techStack: { frontend: ['React'], backend: ['Node.js'], database: ['PostgreSQL'], tools: ['Redis', 'Cron Jobs'] },
  architecture: 'React frontend, Node.js backend with job scheduler, PostgreSQL database, Redis for task queue',
  features: ['Task scheduling', 'Event triggers', 'Execution logs', 'Email notifications', 'Admin dashboard'],
  skillsRequired: ['Backend scheduling', 'REST APIs', 'Database management'],
  learningOutcomes: ['Build automation engines', 'Handle background jobs', 'Design workflow systems'],
  timeline: [
    { week: 1, title: 'System Design', description: 'Workflow engine planning' },
    { week: 2, title: 'Task Scheduler', description: 'Cron and job queue implementation' },
    { week: 3, title: 'Triggers', description: 'Event-based execution system' },
    { week: 4, title: 'Dashboard', description: 'User interface and logs' },
    { week: 5, title: 'Testing', description: 'Performance and reliability testing' }
  ]
},
{
  slug: 'document-management-system',
  title: 'Enterprise Document Management System',
  shortDescription: 'Secure document storage and version control system',
  fullDescription: 'Develop a document management platform that supports file uploads, version tracking, document approval workflows, and role-based access control.',
  domain: 'WEB_DEVELOPMENT',
  difficulty: 'INTERMEDIATE',
  estimatedDuration: '8-10 weeks',
  recommendedYear: 'Third Year',
  primaryTechnology: 'Java',
  techStack: { frontend: ['Angular'], backend: ['Java', 'Spring Boot'], database: ['PostgreSQL'], tools: ['Cloud Storage'] },
  architecture: 'Spring Boot backend with Angular frontend, PostgreSQL storage',
  features: ['File uploads', 'Version history', 'Access control', 'Approval workflows', 'Audit logs'],
  skillsRequired: ['Spring Boot', 'File handling', 'Role-based security'],
  learningOutcomes: ['Build document workflows', 'Implement file storage systems'],
  timeline: [
    { week: 1, title: 'Schema Design', description: 'Database modeling' },
    { week: 2, title: 'Upload System', description: 'File storage integration' },
    { week: 3, title: 'Access Control', description: 'Permission system' },
    { week: 4, title: 'Workflow', description: 'Approval process implementation' }
  ]
},
{
  slug: 'healthcare-prediction-system',
  title: 'Disease Prediction & Healthcare Analytics Platform',
  shortDescription: 'Predict potential diseases based on symptoms and medical data',
  fullDescription: 'Build a healthcare analytics system that predicts diseases based on patient symptoms and medical records using supervised machine learning techniques.',
  domain: 'DATA_SCIENCE',
  difficulty: 'ADVANCED',
  estimatedDuration: '8-10 weeks',
  recommendedYear: 'Final Year',
  primaryTechnology: 'Python',
  techStack: { frontend: ['React'], backend: ['Python', 'FastAPI'], database: ['PostgreSQL'], tools: ['Scikit-learn', 'Pandas'] },
  architecture: 'ML model backend with FastAPI, React dashboard, PostgreSQL database',
  features: ['Symptom input system', 'Prediction engine', 'Medical data visualization', 'Risk scoring'],
  skillsRequired: ['Machine learning', 'Data preprocessing', 'Model evaluation'],
  learningOutcomes: ['Build healthcare ML systems', 'Deploy predictive models'],
  timeline: [
    { week: 1, title: 'Dataset Preparation', description: 'Medical dataset cleaning' },
    { week: 2, title: 'Model Training', description: 'Train classification model' },
    { week: 3, title: 'API Integration', description: 'Deploy prediction API' },
    { week: 4, title: 'Frontend', description: 'User dashboard' }
  ]
},
{
  slug: 'smart-home-automation',
  title: 'Smart Home Automation & Control System',
  shortDescription: 'IoT-based smart home system for device monitoring and control',
  fullDescription: 'Create a smart home automation system to control appliances remotely, monitor energy usage, and automate routines.',
  domain: 'IOT',
  difficulty: 'INTERMEDIATE',
  estimatedDuration: '8-10 weeks',
  recommendedYear: 'Third Year',
  primaryTechnology: 'Python',
  techStack: { frontend: ['React'], backend: ['Python', 'FastAPI'], database: ['PostgreSQL'], tools: ['MQTT', 'Raspberry Pi'] },
  architecture: 'IoT devices connected via MQTT, FastAPI backend, React monitoring dashboard',
  features: ['Remote device control', 'Energy monitoring', 'Automation rules', 'Mobile notifications'],
  skillsRequired: ['IoT fundamentals', 'API development'],
  learningOutcomes: ['Implement IoT automation', 'Build monitoring dashboards'],
  timeline: [
    { week: 1, title: 'Hardware Setup', description: 'Sensor configuration' },
    { week: 2, title: 'Backend APIs', description: 'Device communication' },
    { week: 3, title: 'Frontend', description: 'Control dashboard' },
    { week: 4, title: 'Automation', description: 'Rule engine implementation' }
  ]
},
{
  slug: 'supply-demand-forecasting',
  title: 'Supply & Demand Forecasting System',
  shortDescription: 'Predict product demand using historical sales data',
  fullDescription: 'Develop a forecasting system to predict product demand using time-series analysis and machine learning models.',
  domain: 'DATA_SCIENCE',
  difficulty: 'INTERMEDIATE',
  estimatedDuration: '6-8 weeks',
  recommendedYear: 'Third Year',
  primaryTechnology: 'Python',
  techStack: { frontend: ['React'], backend: ['Python', 'FastAPI'], database: ['PostgreSQL'], tools: ['ARIMA', 'Pandas'] },
  architecture: 'Time-series model backend with FastAPI and React visualization frontend',
  features: ['Demand forecasting', 'Sales analytics', 'Graphical insights'],
  skillsRequired: ['Time-series analysis', 'Data modeling'],
  learningOutcomes: ['Implement forecasting models', 'Build analytics dashboards'],
  timeline: [
    { week: 1, title: 'Data Preparation', description: 'Clean sales data' },
    { week: 2, title: 'Model Building', description: 'Train forecasting model' },
    { week: 3, title: 'Dashboard', description: 'Visualization integration' }
  ]
},
{
  slug: 'cyber-threat-intelligence',
  title: 'Cyber Threat Intelligence Platform',
  shortDescription: 'Monitor and analyze cybersecurity threats in real-time',
  fullDescription: 'Build a cybersecurity intelligence system that collects threat feeds, analyzes patterns, and provides risk alerts.',
  domain: 'CYBERSECURITY',
  difficulty: 'ADVANCED',
  estimatedDuration: '8-10 weeks',
  recommendedYear: 'Final Year',
  primaryTechnology: 'Python',
  techStack: { frontend: ['React'], backend: ['Python', 'FastAPI'], database: ['Elasticsearch'], tools: ['Kibana'] },
  architecture: 'FastAPI backend with Elasticsearch indexing and React dashboard',
  features: ['Threat feed aggregation', 'Risk scoring', 'Alert notifications'],
  skillsRequired: ['Security fundamentals', 'Log analysis'],
  learningOutcomes: ['Design security monitoring systems'],
  timeline: [
    { week: 1, title: 'Threat Feed Setup', description: 'Collect threat intelligence feeds' },
    { week: 2, title: 'Analysis Engine', description: 'Pattern detection logic' },
    { week: 3, title: 'Dashboard', description: 'Threat visualization' }
  ]
},
{
  slug: 'fitness-tracking-mobile-app',
  title: 'Fitness Tracking Mobile Application',
  shortDescription: 'Track workouts, calories, and health metrics',
  fullDescription: 'Develop a React Native fitness tracking app that monitors workouts, tracks calories, and visualizes health metrics.',
  domain: 'MOBILE_DEVELOPMENT',
  difficulty: 'BEGINNER',
  estimatedDuration: '6-8 weeks',
  recommendedYear: 'Second Year',
  primaryTechnology: 'React Native',
  techStack: { frontend: ['React Native'], backend: ['Node.js'], database: ['MongoDB'], tools: ['Chart.js'] },
  architecture: 'React Native frontend with Node.js backend',
  features: ['Workout tracking', 'Calorie tracking', 'Progress charts'],
  skillsRequired: ['Mobile development basics'],
  learningOutcomes: ['Build mobile health apps'],
  timeline: [
    { week: 1, title: 'Setup', description: 'App structure design' },
    { week: 2, title: 'Tracking Module', description: 'Workout logging feature' },
    { week: 3, title: 'Visualization', description: 'Progress charts' }
  ]
},
{
  slug: 'ai-powered-resume-screening',
  title: 'AI Resume Screening & Candidate Ranking System',
  shortDescription: 'Automated resume screening using NLP techniques',
  fullDescription: 'Build an AI-powered resume screening system that ranks candidates based on job descriptions using NLP similarity models.',
  domain: 'MACHINE_LEARNING',
  difficulty: 'ADVANCED',
  estimatedDuration: '8-10 weeks',
  recommendedYear: 'Final Year',
  primaryTechnology: 'Python',
  techStack: { frontend: ['React'], backend: ['Python', 'FastAPI'], database: ['PostgreSQL'], tools: ['Transformers', 'Scikit-learn'] },
  architecture: 'FastAPI backend with NLP ranking model, React dashboard',
  features: ['Resume parsing', 'Candidate ranking', 'Keyword extraction'],
  skillsRequired: ['NLP basics', 'Machine learning'],
  learningOutcomes: ['Implement NLP ranking systems'],
  timeline: [
    { week: 1, title: 'Dataset Preparation', description: 'Resume data processing' },
    { week: 2, title: 'Model Training', description: 'Similarity model development' },
    { week: 3, title: 'API Integration', description: 'Deploy screening API' }
  ]
}

];
