import { PrismaClient, PostType, ProjectDomain, ProjectDifficulty } from '@prisma/client';

const prisma = new PrismaClient({
  datasources: {
    db: {
      url: process.env.DATABASE_URL,
    },
  },
});

const IDEAS = [
  {
    title: 'AI-Powered Code Review Assistant',
    shortDescription: 'An intelligent tool that analyzes code quality, suggests improvements, and detects potential bugs using machine learning algorithms.',
    fullDescription: 'This project aims to create an AI-powered code review assistant that integrates with popular version control systems like GitHub and GitLab. The tool will use advanced machine learning models to analyze code patterns, identify potential bugs, suggest performance optimizations, and ensure adherence to coding standards. It will provide real-time feedback during pull requests and offer detailed explanations for each suggestion. The system will learn from accepted and rejected suggestions to improve its accuracy over time.',
    domain: 'AI_ML' as ProjectDomain,
    difficulty: 'ADVANCED' as ProjectDifficulty,
    tags: ['AI', 'Machine Learning', 'Code Quality', 'DevOps', 'Automation'],
    techStack: ['Python', 'TensorFlow', 'FastAPI', 'Docker', 'PostgreSQL'],
    estimatedDuration: '4-6 months',
  },
  {
    title: 'Decentralized Social Media Platform',
    shortDescription: 'A blockchain-based social network where users own their data and content, with built-in monetization through cryptocurrency.',
    fullDescription: 'Build a revolutionary social media platform on blockchain technology that gives users complete control over their data and content. The platform will use smart contracts for content ownership, implement a token-based economy for content monetization, and provide decentralized storage using IPFS. Users can earn tokens through engagement, and creators can monetize their content directly without intermediaries. The platform will feature end-to-end encryption, censorship resistance, and transparent content moderation through community governance.',
    domain: 'BLOCKCHAIN' as ProjectDomain,
    difficulty: 'EXPERT' as ProjectDifficulty,
    tags: ['Blockchain', 'Web3', 'Cryptocurrency', 'Decentralization', 'Smart Contracts'],
    techStack: ['Solidity', 'Ethereum', 'React', 'IPFS', 'Web3.js', 'Node.js'],
    estimatedDuration: '8-12 months',
  },
  {
    title: 'Real-Time Collaborative Whiteboard',
    shortDescription: 'An interactive online whiteboard with real-time collaboration, perfect for remote teams and online education.',
    fullDescription: 'Create a feature-rich collaborative whiteboard application that enables teams to brainstorm, design, and plan together in real-time. The platform will support unlimited canvas size, various drawing tools, sticky notes, shapes, and image uploads. It will include features like video chat integration, session recording, template library, and export options. The application will use WebSocket for real-time synchronization and implement conflict resolution for simultaneous edits. Perfect for remote teams, online classrooms, and design workshops.',
    domain: 'WEB_DEVELOPMENT' as ProjectDomain,
    difficulty: 'INTERMEDIATE' as ProjectDifficulty,
    tags: ['Real-time', 'Collaboration', 'WebSocket', 'Canvas', 'Remote Work'],
    techStack: ['React', 'Node.js', 'Socket.io', 'Canvas API', 'MongoDB', 'WebRTC'],
    estimatedDuration: '3-4 months',
  },
  {
    title: 'Smart Home Energy Management System',
    shortDescription: 'IoT-based system that optimizes home energy consumption using AI to reduce electricity bills and carbon footprint.',
    fullDescription: 'Develop an intelligent energy management system for smart homes that monitors, analyzes, and optimizes energy consumption. The system will use IoT sensors to track energy usage of individual appliances, predict consumption patterns using machine learning, and automatically adjust settings to minimize waste. It will integrate with smart thermostats, lighting systems, and solar panels. The mobile app will provide real-time insights, cost savings reports, and recommendations for energy-efficient practices. The system will also support time-of-use pricing optimization and renewable energy integration.',
    domain: 'IOT' as ProjectDomain,
    difficulty: 'ADVANCED' as ProjectDifficulty,
    tags: ['IoT', 'Smart Home', 'Energy', 'Sustainability', 'AI'],
    techStack: ['Python', 'Raspberry Pi', 'MQTT', 'React Native', 'InfluxDB', 'TensorFlow'],
    estimatedDuration: '5-7 months',
  },
  {
    title: 'Automated Penetration Testing Framework',
    shortDescription: 'A comprehensive security testing tool that automatically identifies vulnerabilities in web applications and networks.',
    fullDescription: 'Create an advanced penetration testing framework that automates the discovery and exploitation of security vulnerabilities. The tool will perform comprehensive scans including SQL injection, XSS, CSRF, authentication bypass, and configuration issues. It will generate detailed reports with severity ratings, proof-of-concept exploits, and remediation recommendations. The framework will support custom plugins, integrate with CI/CD pipelines, and provide a user-friendly dashboard for security teams. It will also include compliance checking for standards like OWASP Top 10 and PCI DSS.',
    domain: 'CYBERSECURITY' as ProjectDomain,
    difficulty: 'EXPERT' as ProjectDifficulty,
    tags: ['Security', 'Penetration Testing', 'Vulnerability', 'Automation', 'DevSecOps'],
    techStack: ['Python', 'Metasploit', 'Nmap', 'Burp Suite API', 'Django', 'PostgreSQL'],
    estimatedDuration: '6-9 months',
  },
  {
    title: 'Cross-Platform Fitness Tracking App',
    shortDescription: 'A comprehensive fitness app with workout plans, nutrition tracking, and social features to keep users motivated.',
    fullDescription: 'Build a full-featured fitness application that helps users achieve their health goals through personalized workout plans, nutrition tracking, and community support. The app will use device sensors and wearable integration to track activities, calories, and vital signs. It will feature AI-powered workout recommendations, meal planning with barcode scanning, progress visualization, and achievement badges. Social features include challenges, leaderboards, and workout sharing. The app will support offline mode and sync across devices.',
    domain: 'MOBILE_DEVELOPMENT' as ProjectDomain,
    difficulty: 'INTERMEDIATE' as ProjectDifficulty,
    tags: ['Mobile', 'Fitness', 'Health', 'Social', 'Wearables'],
    techStack: ['React Native', 'Node.js', 'MongoDB', 'Firebase', 'HealthKit', 'Google Fit'],
    estimatedDuration: '4-5 months',
  },
  {
    title: 'Serverless E-Commerce Platform',
    shortDescription: 'A scalable, cost-effective e-commerce solution built entirely on serverless architecture with automatic scaling.',
    fullDescription: 'Design and implement a modern e-commerce platform using serverless technologies for maximum scalability and cost efficiency. The platform will handle product catalogs, shopping carts, payment processing, order management, and inventory tracking. It will use event-driven architecture for real-time updates, implement microservices for different functionalities, and leverage CDN for fast content delivery. Features include multi-currency support, advanced search with filters, customer reviews, and admin dashboard. The serverless approach ensures automatic scaling during traffic spikes and pay-per-use pricing.',
    domain: 'CLOUD_COMPUTING' as ProjectDomain,
    difficulty: 'ADVANCED' as ProjectDifficulty,
    tags: ['Serverless', 'E-commerce', 'Cloud', 'Microservices', 'Scalability'],
    techStack: ['AWS Lambda', 'API Gateway', 'DynamoDB', 'S3', 'CloudFront', 'Stripe'],
    estimatedDuration: '5-6 months',
  },
  {
    title: 'Interactive Data Visualization Dashboard',
    shortDescription: 'A powerful analytics platform that transforms complex datasets into beautiful, interactive visualizations and insights.',
    fullDescription: 'Create a sophisticated data visualization platform that enables users to explore and understand complex datasets through interactive charts, graphs, and dashboards. The platform will support multiple data sources including databases, APIs, and file uploads. It will offer a drag-and-drop interface for creating custom dashboards, real-time data updates, and collaborative features for team sharing. Advanced features include predictive analytics, anomaly detection, and automated insight generation. The platform will support various chart types, custom themes, and export options for presentations.',
    domain: 'DATA_SCIENCE' as ProjectDomain,
    difficulty: 'INTERMEDIATE' as ProjectDifficulty,
    tags: ['Data Visualization', 'Analytics', 'Dashboard', 'Business Intelligence', 'Charts'],
    techStack: ['React', 'D3.js', 'Python', 'Pandas', 'PostgreSQL', 'Redis'],
    estimatedDuration: '3-5 months',
  },
  {
    title: 'Multiplayer VR Escape Room Game',
    shortDescription: 'An immersive virtual reality escape room experience with puzzle-solving and teamwork in stunning 3D environments.',
    fullDescription: 'Develop an engaging multiplayer VR escape room game that challenges players to solve intricate puzzles and work together to escape themed rooms. The game will feature photorealistic 3D environments, physics-based interactions, voice chat, and dynamic difficulty adjustment. Players will explore mysterious locations, discover hidden clues, manipulate objects, and solve complex puzzles within a time limit. The game will include multiple themed rooms, a level editor for community-created content, and a progression system with unlockable items. Cross-platform support for major VR headsets.',
    domain: 'GAME_DEVELOPMENT' as ProjectDomain,
    difficulty: 'EXPERT' as ProjectDifficulty,
    tags: ['VR', 'Gaming', 'Multiplayer', 'Unity', '3D', 'Puzzle'],
    techStack: ['Unity', 'C#', 'Photon', 'Blender', 'FMOD', 'SteamVR'],
    estimatedDuration: '8-10 months',
  },
  {
    title: 'AI-Powered Resume Builder',
    shortDescription: 'An intelligent resume creation tool that uses AI to optimize content, format, and keywords for specific job applications.',
    fullDescription: 'Build a smart resume builder that leverages artificial intelligence to help job seekers create compelling, ATS-friendly resumes. The tool will analyze job descriptions and suggest relevant skills, experiences, and keywords to include. It will offer industry-specific templates, real-time content optimization, and grammar checking. The AI will provide personalized recommendations for improving resume impact, suggest action verbs, and optimize formatting for applicant tracking systems. Additional features include cover letter generation, LinkedIn profile optimization, and interview preparation tips.',
    domain: 'AI_ML' as ProjectDomain,
    difficulty: 'INTERMEDIATE' as ProjectDifficulty,
    tags: ['AI', 'Career', 'NLP', 'Job Search', 'Automation'],
    techStack: ['React', 'Python', 'OpenAI API', 'Node.js', 'MongoDB', 'PDF.js'],
    estimatedDuration: '2-3 months',
  },
  {
    title: 'Blockchain-Based Supply Chain Tracker',
    shortDescription: 'A transparent supply chain management system using blockchain to track products from manufacture to delivery.',
    fullDescription: 'Implement a blockchain-based supply chain tracking system that provides end-to-end visibility and transparency for product journeys. The platform will record every transaction and movement on an immutable ledger, enabling stakeholders to verify authenticity, track location, and ensure compliance. Features include QR code scanning, real-time notifications, temperature monitoring for perishables, and automated smart contracts for payments. The system will help prevent counterfeiting, reduce fraud, and improve efficiency. It will support multiple stakeholders including manufacturers, distributors, retailers, and consumers.',
    domain: 'BLOCKCHAIN' as ProjectDomain,
    difficulty: 'ADVANCED' as ProjectDifficulty,
    tags: ['Blockchain', 'Supply Chain', 'Logistics', 'Smart Contracts', 'IoT'],
    techStack: ['Hyperledger Fabric', 'Node.js', 'React', 'MongoDB', 'Docker', 'Kubernetes'],
    estimatedDuration: '6-8 months',
  },
  {
    title: 'Progressive Web App for Local Services',
    shortDescription: 'A PWA connecting local service providers with customers, featuring booking, payments, and reviews.',
    fullDescription: 'Create a progressive web application that connects local service providers (plumbers, electricians, cleaners, etc.) with customers in their area. The platform will feature service provider profiles, real-time availability, instant booking, secure payments, and customer reviews. It will include geolocation-based search, price comparison, service history tracking, and automated reminders. The PWA will work offline, send push notifications, and provide a native app-like experience. Additional features include background checks verification, insurance tracking, and dispute resolution system.',
    domain: 'WEB_DEVELOPMENT' as ProjectDomain,
    difficulty: 'INTERMEDIATE' as ProjectDifficulty,
    tags: ['PWA', 'Local Services', 'Marketplace', 'Booking', 'Payments'],
    techStack: ['Next.js', 'Service Workers', 'Stripe', 'Google Maps API', 'PostgreSQL', 'Redis'],
    estimatedDuration: '4-5 months',
  },
  {
    title: 'Smart Agriculture Monitoring System',
    shortDescription: 'IoT solution for precision farming with soil sensors, weather monitoring, and automated irrigation control.',
    fullDescription: 'Develop a comprehensive IoT-based agriculture monitoring system that helps farmers optimize crop yields and resource usage. The system will deploy sensors to monitor soil moisture, pH levels, temperature, humidity, and nutrient content. It will integrate weather forecasts, control automated irrigation systems, and provide crop health insights using drone imagery and AI analysis. The mobile app will send alerts for pest detection, disease outbreaks, and optimal harvest times. Features include water usage optimization, fertilizer recommendations, and yield prediction models.',
    domain: 'IOT' as ProjectDomain,
    difficulty: 'ADVANCED' as ProjectDifficulty,
    tags: ['IoT', 'Agriculture', 'Sensors', 'Automation', 'Sustainability'],
    techStack: ['Arduino', 'Raspberry Pi', 'Python', 'MQTT', 'React Native', 'InfluxDB'],
    estimatedDuration: '5-7 months',
  },
  {
    title: 'Zero-Knowledge Authentication System',
    shortDescription: 'A privacy-focused authentication system using zero-knowledge proofs for secure, passwordless login.',
    fullDescription: 'Build an advanced authentication system based on zero-knowledge proof cryptography that enables users to prove their identity without revealing passwords or sensitive information. The system will eliminate password storage vulnerabilities, prevent phishing attacks, and ensure user privacy. It will support biometric authentication, hardware security keys, and multi-factor authentication. The solution will be easy to integrate into existing applications through SDKs and APIs. Features include session management, device fingerprinting, anomaly detection, and compliance with privacy regulations like GDPR.',
    domain: 'CYBERSECURITY' as ProjectDomain,
    difficulty: 'EXPERT' as ProjectDifficulty,
    tags: ['Security', 'Cryptography', 'Authentication', 'Privacy', 'Zero-Knowledge'],
    techStack: ['Rust', 'WebAuthn', 'Node.js', 'PostgreSQL', 'Redis', 'Docker'],
    estimatedDuration: '6-8 months',
  },
  {
    title: 'Mental Health Support Mobile App',
    shortDescription: 'A compassionate mental health app offering mood tracking, meditation, therapy resources, and crisis support.',
    fullDescription: 'Create a comprehensive mental health support application that provides users with tools and resources for emotional well-being. The app will feature daily mood tracking with insights, guided meditation and breathing exercises, cognitive behavioral therapy (CBT) techniques, and journaling. It will include a crisis support hotline directory, anonymous peer support groups, and connections to licensed therapists. The app will use AI to identify patterns and provide personalized recommendations. Features include progress tracking, achievement badges, and privacy-focused design with end-to-end encryption.',
    domain: 'MOBILE_DEVELOPMENT' as ProjectDomain,
    difficulty: 'INTERMEDIATE' as ProjectDifficulty,
    tags: ['Mental Health', 'Wellness', 'Mobile', 'Healthcare', 'AI'],
    techStack: ['Flutter', 'Firebase', 'Node.js', 'MongoDB', 'TensorFlow Lite', 'Twilio'],
    estimatedDuration: '4-6 months',
  },
  {
    title: 'Multi-Cloud Cost Optimization Platform',
    shortDescription: 'An intelligent platform that analyzes and optimizes cloud spending across AWS, Azure, and Google Cloud.',
    fullDescription: 'Develop a comprehensive cloud cost management platform that helps organizations optimize their multi-cloud spending. The platform will analyze usage patterns, identify waste, recommend right-sizing opportunities, and automate cost-saving actions. It will provide detailed cost breakdowns by service, project, and team, with forecasting and budget alerts. Features include reserved instance recommendations, spot instance management, unused resource detection, and compliance monitoring. The platform will support custom policies, automated remediation, and integration with financial systems for chargeback and showback.',
    domain: 'CLOUD_COMPUTING' as ProjectDomain,
    difficulty: 'ADVANCED' as ProjectDifficulty,
    tags: ['Cloud', 'Cost Optimization', 'FinOps', 'Multi-Cloud', 'Analytics'],
    techStack: ['Python', 'React', 'AWS SDK', 'Azure SDK', 'GCP SDK', 'PostgreSQL', 'Grafana'],
    estimatedDuration: '5-7 months',
  },
  {
    title: 'Predictive Maintenance Analytics Platform',
    shortDescription: 'AI-powered system that predicts equipment failures and optimizes maintenance schedules for industrial machinery.',
    fullDescription: 'Build an advanced predictive maintenance platform that uses machine learning to forecast equipment failures before they occur. The system will collect data from IoT sensors monitoring vibration, temperature, pressure, and other parameters. It will analyze historical failure patterns, identify anomalies, and predict remaining useful life of components. The platform will generate automated work orders, optimize maintenance schedules, and track spare parts inventory. Features include root cause analysis, maintenance cost tracking, and integration with existing CMMS systems. This reduces downtime, extends equipment life, and lowers maintenance costs.',
    domain: 'DATA_SCIENCE' as ProjectDomain,
    difficulty: 'EXPERT' as ProjectDifficulty,
    tags: ['Predictive Analytics', 'Machine Learning', 'IoT', 'Industrial', 'Maintenance'],
    techStack: ['Python', 'Scikit-learn', 'Apache Kafka', 'TimescaleDB', 'React', 'Docker'],
    estimatedDuration: '6-9 months',
  },
  {
    title: 'Open-World Survival Game',
    shortDescription: 'A massive multiplayer survival game with crafting, base building, and dynamic weather in a procedurally generated world.',
    fullDescription: 'Create an immersive open-world survival game where players must gather resources, craft tools, build shelters, and survive against environmental hazards and wildlife. The game will feature a procedurally generated world with diverse biomes, dynamic day-night cycles, and realistic weather systems. Players can form tribes, engage in PvP combat, tame animals, and explore dungeons. The game will include a deep crafting system, skill progression, farming mechanics, and seasonal events. Server-side architecture will support thousands of concurrent players with persistent world state and anti-cheat systems.',
    domain: 'GAME_DEVELOPMENT' as ProjectDomain,
    difficulty: 'EXPERT' as ProjectDifficulty,
    tags: ['Gaming', 'Multiplayer', 'Survival', 'Open World', 'Procedural Generation'],
    techStack: ['Unreal Engine', 'C++', 'PlayFab', 'AWS', 'Photon', 'Wwise'],
    estimatedDuration: '12-18 months',
  },
  {
    title: 'AI Content Moderation System',
    shortDescription: 'An intelligent moderation tool that automatically detects and filters inappropriate content across text, images, and videos.',
    fullDescription: 'Develop a comprehensive AI-powered content moderation system that protects online communities from harmful content. The system will use computer vision and natural language processing to detect hate speech, violence, nudity, spam, and misinformation. It will support multiple languages, provide confidence scores, and allow human review for edge cases. Features include real-time moderation, automated actions (remove, flag, warn), user reputation scoring, and detailed analytics. The system will continuously learn from moderator decisions and adapt to community-specific rules. API-first design for easy integration.',
    domain: 'AI_ML' as ProjectDomain,
    difficulty: 'ADVANCED' as ProjectDifficulty,
    tags: ['AI', 'Content Moderation', 'Computer Vision', 'NLP', 'Safety'],
    techStack: ['Python', 'TensorFlow', 'OpenCV', 'FastAPI', 'Redis', 'PostgreSQL'],
    estimatedDuration: '5-7 months',
  },
  {
    title: 'Decentralized File Storage Network',
    shortDescription: 'A peer-to-peer file storage system using blockchain for secure, censorship-resistant data storage.',
    fullDescription: 'Build a decentralized file storage network where users can store and share files across a distributed network of nodes. The system will use blockchain for file metadata and access control, implement encryption for privacy, and provide redundancy through file sharding. Users can earn tokens by providing storage space and pay tokens to store files. Features include file versioning, sharing permissions, automatic backup, and CDN-like performance through edge caching. The network will be resistant to censorship, single points of failure, and data loss. Client applications for desktop and mobile platforms.',
    domain: 'BLOCKCHAIN' as ProjectDomain,
    difficulty: 'EXPERT' as ProjectDifficulty,
    tags: ['Blockchain', 'Decentralization', 'Storage', 'P2P', 'Encryption'],
    techStack: ['Go', 'IPFS', 'Ethereum', 'React', 'Electron', 'WebAssembly'],
    estimatedDuration: '8-12 months',
  },
  {
    title: 'Real-Time Language Translation App',
    shortDescription: 'A mobile app providing instant voice and text translation with offline support for travelers and language learners.',
    fullDescription: 'Create a powerful language translation application that breaks down communication barriers with real-time voice and text translation. The app will support 100+ languages, work offline with downloaded language packs, and provide conversation mode for two-way communication. Features include camera translation for signs and menus, phrasebook with common expressions, pronunciation guides, and language learning tools. The app will use neural machine translation for accuracy, support dialect variations, and include cultural tips. Additional features include saved translations, favorites, and integration with messaging apps.',
    domain: 'MOBILE_DEVELOPMENT' as ProjectDomain,
    difficulty: 'ADVANCED' as ProjectDifficulty,
    tags: ['Translation', 'NLP', 'Mobile', 'AI', 'Travel'],
    techStack: ['React Native', 'TensorFlow Lite', 'Google Cloud Translation', 'SQLite', 'Firebase'],
    estimatedDuration: '4-6 months',
  },
  {
    title: 'Microservices Orchestration Platform',
    shortDescription: 'A comprehensive platform for deploying, managing, and monitoring microservices with auto-scaling and service mesh.',
    fullDescription: 'Develop an enterprise-grade microservices orchestration platform that simplifies the deployment and management of distributed applications. The platform will provide service discovery, load balancing, circuit breakers, and distributed tracing. It will include a service mesh for secure service-to-service communication, automatic scaling based on metrics, and blue-green deployments. Features include centralized logging, metrics aggregation, alerting, and a visual dashboard for monitoring service health. The platform will support multiple cloud providers, implement GitOps workflows, and provide disaster recovery capabilities.',
    domain: 'CLOUD_COMPUTING' as ProjectDomain,
    difficulty: 'EXPERT' as ProjectDifficulty,
    tags: ['Microservices', 'Kubernetes', 'DevOps', 'Cloud', 'Orchestration'],
    techStack: ['Kubernetes', 'Istio', 'Prometheus', 'Grafana', 'Helm', 'ArgoCD'],
    estimatedDuration: '7-10 months',
  },
  {
    title: 'Network Traffic Analyzer',
    shortDescription: 'A powerful network monitoring tool that analyzes traffic patterns, detects anomalies, and identifies security threats.',
    fullDescription: 'Build a comprehensive network traffic analysis tool that provides deep visibility into network activity and security threats. The system will capture and analyze packets in real-time, identify protocols and applications, and detect suspicious patterns. It will use machine learning to establish baseline behavior and alert on anomalies. Features include bandwidth monitoring, top talkers identification, protocol distribution analysis, and forensic capabilities. The tool will detect DDoS attacks, data exfiltration, malware communication, and policy violations. Includes customizable dashboards, automated reports, and integration with SIEM systems.',
    domain: 'CYBERSECURITY' as ProjectDomain,
    difficulty: 'ADVANCED' as ProjectDifficulty,
    tags: ['Network Security', 'Traffic Analysis', 'Monitoring', 'Threat Detection', 'Forensics'],
    techStack: ['Python', 'Wireshark', 'Elasticsearch', 'Kibana', 'Suricata', 'Zeek'],
    estimatedDuration: '5-7 months',
  },
  {
    title: 'Smart City Traffic Management',
    shortDescription: 'An IoT-based traffic management system that optimizes traffic flow and reduces congestion using real-time data.',
    fullDescription: 'Design an intelligent traffic management system for smart cities that uses IoT sensors and AI to optimize traffic flow. The system will monitor traffic density, vehicle speeds, and parking availability in real-time. It will dynamically adjust traffic light timings, suggest alternate routes, and predict congestion. Features include emergency vehicle priority routing, public transit optimization, air quality monitoring, and incident detection. The platform will provide a mobile app for citizens with real-time traffic updates, parking availability, and public transit schedules. Integration with city infrastructure and emergency services.',
    domain: 'IOT' as ProjectDomain,
    difficulty: 'EXPERT' as ProjectDifficulty,
    tags: ['IoT', 'Smart City', 'Traffic', 'AI', 'Urban Planning'],
    techStack: ['Python', 'TensorFlow', 'MQTT', 'Apache Kafka', 'React', 'PostgreSQL', 'Redis'],
    estimatedDuration: '8-12 months',
  },
  {
    title: 'Customer Churn Prediction System',
    shortDescription: 'A machine learning platform that predicts customer churn and recommends retention strategies for businesses.',
    fullDescription: 'Create an advanced analytics platform that helps businesses identify customers at risk of churning and take proactive retention actions. The system will analyze customer behavior, transaction history, support interactions, and engagement metrics to predict churn probability. It will segment customers by risk level, identify key churn indicators, and recommend personalized retention strategies. Features include A/B testing for retention campaigns, ROI calculation, automated alerts, and integration with CRM systems. The platform will provide explainable AI insights to help understand why customers leave and what actions are most effective.',
    domain: 'DATA_SCIENCE' as ProjectDomain,
    difficulty: 'ADVANCED' as ProjectDifficulty,
    tags: ['Machine Learning', 'Predictive Analytics', 'Customer Retention', 'Business Intelligence'],
    techStack: ['Python', 'Scikit-learn', 'XGBoost', 'React', 'PostgreSQL', 'Apache Airflow'],
    estimatedDuration: '4-6 months',
  },
  {
    title: 'Indie Game Publishing Platform',
    shortDescription: 'A marketplace and distribution platform specifically designed for indie game developers to publish and monetize their games.',
    fullDescription: 'Build a comprehensive platform that empowers indie game developers to publish, distribute, and monetize their games. The platform will handle game hosting, payment processing, DRM, automatic updates, and community features. It will include developer analytics, revenue sharing, promotional tools, and discovery algorithms. Features include user reviews, wishlists, achievements, cloud saves, and social features. The platform will support multiple platforms (PC, Mac, Linux), provide SDK for easy integration, and offer lower commission rates than traditional stores. Community features include forums, mod support, and developer blogs.',
    domain: 'GAME_DEVELOPMENT' as ProjectDomain,
    difficulty: 'ADVANCED' as ProjectDifficulty,
    tags: ['Gaming', 'Marketplace', 'Indie', 'Distribution', 'Monetization'],
    techStack: ['Node.js', 'React', 'PostgreSQL', 'Redis', 'AWS S3', 'Stripe', 'Docker'],
    estimatedDuration: '6-9 months',
  },
  {
    title: 'Voice-Controlled Smart Assistant',
    shortDescription: 'An AI-powered voice assistant with natural language understanding, task automation, and smart home integration.',
    fullDescription: 'Develop a sophisticated voice-controlled AI assistant that understands natural language, performs tasks, and controls smart home devices. The assistant will support multi-turn conversations, context awareness, and personalized responses. It will integrate with calendars, emails, reminders, weather, news, and music services. Features include voice authentication, multi-language support, offline capabilities, and privacy-focused design with local processing. The assistant will learn user preferences, support custom commands, and integrate with IoT devices. Includes wake word detection, noise cancellation, and continuous learning from interactions.',
    domain: 'AI_ML' as ProjectDomain,
    difficulty: 'EXPERT' as ProjectDifficulty,
    tags: ['AI', 'Voice Assistant', 'NLP', 'Smart Home', 'Automation'],
    techStack: ['Python', 'TensorFlow', 'Rasa', 'PyTorch', 'MQTT', 'React Native'],
    estimatedDuration: '7-10 months',
  },
  {
    title: 'API Gateway and Management Platform',
    shortDescription: 'A comprehensive API gateway with rate limiting, authentication, monitoring, and developer portal.',
    fullDescription: 'Create an enterprise-grade API gateway and management platform that serves as a single entry point for all API traffic. The platform will provide request routing, load balancing, rate limiting, and caching. It will support multiple authentication methods (OAuth, JWT, API keys), implement request/response transformation, and provide detailed analytics. Features include API versioning, documentation generation, developer portal, mock servers, and testing tools. The gateway will ensure security with threat detection, DDoS protection, and compliance monitoring. Includes SDKs for popular languages and integration with CI/CD pipelines.',
    domain: 'WEB_DEVELOPMENT' as ProjectDomain,
    difficulty: 'ADVANCED' as ProjectDifficulty,
    tags: ['API', 'Gateway', 'Microservices', 'Security', 'DevOps'],
    techStack: ['Node.js', 'Kong', 'Redis', 'PostgreSQL', 'React', 'Prometheus', 'Docker'],
    estimatedDuration: '5-7 months',
  },
];

const COLLABORATIONS = [
  {
    title: 'Open Source Healthcare Management System',
    shortDescription: 'Building a comprehensive, HIPAA-compliant healthcare management system for clinics and hospitals.',
    fullDescription: 'We are developing an open-source healthcare management system that will revolutionize how small to medium-sized clinics manage patient care. The system will include electronic health records (EHR), appointment scheduling, billing, inventory management, and telemedicine capabilities. We need developers passionate about healthcare technology to help build a secure, scalable, and user-friendly platform. The project will follow HIPAA compliance standards, implement role-based access control, and support multiple languages. This is an opportunity to make healthcare more accessible and efficient worldwide.',
    domain: 'WEB_DEVELOPMENT' as ProjectDomain,
    difficulty: 'ADVANCED' as ProjectDifficulty,
    tags: ['Healthcare', 'Open Source', 'EHR', 'HIPAA', 'Telemedicine'],
    techStack: ['React', 'Node.js', 'PostgreSQL', 'Docker', 'WebRTC', 'Redis'],
    estimatedDuration: '8-12 months',
    requiredCollaborators: 5,
    requiredSkills: ['Full-stack Development', 'Healthcare IT', 'Security', 'Database Design', 'UI/UX'],
  },
  {
    title: 'Climate Change Data Visualization',
    shortDescription: 'Creating an interactive platform to visualize global climate data and raise environmental awareness.',
    fullDescription: 'Join us in building a powerful data visualization platform that makes climate change data accessible and understandable to everyone. We will aggregate data from multiple sources including NASA, NOAA, and research institutions to create compelling visualizations of temperature changes, sea level rise, carbon emissions, and extreme weather events. The platform will feature interactive maps, time-series animations, predictive models, and educational content. We are looking for data scientists, frontend developers, and climate enthusiasts to help us create a tool that can drive climate action and policy changes.',
    domain: 'DATA_SCIENCE' as ProjectDomain,
    difficulty: 'INTERMEDIATE' as ProjectDifficulty,
    tags: ['Climate', 'Data Visualization', 'Environment', 'Open Data', 'Education'],
    techStack: ['Python', 'D3.js', 'React', 'Pandas', 'Mapbox', 'PostgreSQL'],
    estimatedDuration: '4-6 months',
    requiredCollaborators: 4,
    requiredSkills: ['Data Science', 'Frontend Development', 'Data Visualization', 'Python', 'JavaScript'],
  },
  {
    title: 'Decentralized Voting Platform',
    shortDescription: 'Developing a secure, transparent blockchain-based voting system for elections and governance.',
    fullDescription: 'We are creating a revolutionary voting platform using blockchain technology to ensure election integrity, transparency, and accessibility. The system will provide end-to-end verifiable voting, prevent double voting, maintain voter anonymity, and create an immutable audit trail. We need blockchain developers, cryptography experts, and security specialists to build a platform that can be used for government elections, corporate governance, and community decisions. The project will include voter registration, identity verification, ballot creation, real-time results, and comprehensive auditing tools. This could transform democratic processes worldwide.',
    domain: 'BLOCKCHAIN' as ProjectDomain,
    difficulty: 'EXPERT' as ProjectDifficulty,
    tags: ['Blockchain', 'Voting', 'Democracy', 'Security', 'Governance'],
    techStack: ['Solidity', 'Ethereum', 'React', 'Node.js', 'IPFS', 'Zero-Knowledge Proofs'],
    estimatedDuration: '10-14 months',
    requiredCollaborators: 6,
    requiredSkills: ['Blockchain Development', 'Smart Contracts', 'Cryptography', 'Security', 'Full-stack'],
  },
  {
    title: 'AI-Powered Educational Platform',
    shortDescription: 'Building an adaptive learning platform that personalizes education using AI for students worldwide.',
    fullDescription: 'Join our mission to democratize education through an AI-powered learning platform that adapts to each student\'s pace and learning style. The platform will offer courses in STEM subjects, provide real-time feedback, generate personalized study plans, and track progress. We are looking for machine learning engineers, educators, and full-stack developers to create an engaging, effective learning experience. Features will include interactive exercises, video lessons, peer collaboration, gamification, and teacher dashboards. Our goal is to make quality education accessible to underserved communities globally.',
    domain: 'AI_ML' as ProjectDomain,
    difficulty: 'ADVANCED' as ProjectDifficulty,
    tags: ['Education', 'AI', 'E-learning', 'Adaptive Learning', 'EdTech'],
    techStack: ['Python', 'TensorFlow', 'React', 'Node.js', 'MongoDB', 'WebRTC'],
    estimatedDuration: '7-10 months',
    requiredCollaborators: 5,
    requiredSkills: ['Machine Learning', 'Full-stack Development', 'Educational Design', 'UI/UX', 'Backend'],
  },
  {
    title: 'Open Source Cybersecurity Training Lab',
    shortDescription: 'Creating a hands-on cybersecurity training platform with realistic attack scenarios and challenges.',
    fullDescription: 'We are building a comprehensive cybersecurity training platform that provides hands-on experience with real-world security scenarios. The platform will feature vulnerable applications, capture-the-flag challenges, penetration testing labs, and guided tutorials. We need security researchers, developers, and educators to create engaging content and a robust infrastructure. The platform will support multiple difficulty levels, track progress, provide hints, and offer certifications. This project aims to address the cybersecurity skills gap by providing free, accessible training to aspiring security professionals worldwide.',
    domain: 'CYBERSECURITY' as ProjectDomain,
    difficulty: 'ADVANCED' as ProjectDifficulty,
    tags: ['Cybersecurity', 'Training', 'CTF', 'Education', 'Penetration Testing'],
    techStack: ['Docker', 'Kubernetes', 'Python', 'React', 'PostgreSQL', 'Linux'],
    estimatedDuration: '6-9 months',
    requiredCollaborators: 4,
    requiredSkills: ['Cybersecurity', 'DevOps', 'Full-stack Development', 'Content Creation', 'Linux'],
  },
  {
    title: 'Mental Health Support Network',
    shortDescription: 'Building a peer-to-peer mental health support platform with anonymous chat and professional resources.',
    fullDescription: 'Join us in creating a safe, supportive platform for people struggling with mental health challenges. The platform will connect users with trained peer supporters, provide anonymous chat rooms, offer self-help resources, and facilitate connections to professional help. We are looking for developers, mental health professionals, and UX designers who are passionate about mental health advocacy. Features will include crisis intervention protocols, mood tracking, meditation guides, and community forums. Privacy and security are paramount, with end-to-end encryption and strict data protection. Together, we can save lives and reduce stigma.',
    domain: 'MOBILE_DEVELOPMENT' as ProjectDomain,
    difficulty: 'INTERMEDIATE' as ProjectDifficulty,
    tags: ['Mental Health', 'Social Impact', 'Healthcare', 'Community', 'Support'],
    techStack: ['React Native', 'Node.js', 'MongoDB', 'Socket.io', 'Firebase', 'Twilio'],
    estimatedDuration: '5-7 months',
    requiredCollaborators: 4,
    requiredSkills: ['Mobile Development', 'Backend Development', 'UI/UX Design', 'Security', 'Healthcare'],
  },
  {
    title: 'Sustainable Agriculture Platform',
    shortDescription: 'Developing an IoT and AI platform to help small farmers optimize yields and practice sustainable farming.',
    fullDescription: 'We are creating a technology platform to empower small-scale farmers with tools for sustainable, profitable agriculture. The system will use IoT sensors for soil and weather monitoring, AI for crop disease detection, and provide recommendations for organic farming practices. We need IoT engineers, data scientists, agronomists, and mobile developers. The platform will include a mobile app with offline capabilities, marketplace for selling produce, access to micro-loans, and a knowledge base of sustainable farming techniques. This project can improve food security and farmer livelihoods in developing regions.',
    domain: 'IOT' as ProjectDomain,
    difficulty: 'ADVANCED' as ProjectDifficulty,
    tags: ['Agriculture', 'IoT', 'Sustainability', 'AI', 'Social Impact'],
    techStack: ['Arduino', 'Python', 'TensorFlow', 'React Native', 'MQTT', 'PostgreSQL'],
    estimatedDuration: '8-11 months',
    requiredCollaborators: 5,
    requiredSkills: ['IoT Development', 'Machine Learning', 'Mobile Development', 'Agriculture', 'Data Science'],
  },
  {
    title: 'Cloud-Native Disaster Recovery System',
    shortDescription: 'Building an automated disaster recovery solution for cloud infrastructure with one-click failover.',
    fullDescription: 'Join our team to build a comprehensive disaster recovery solution for cloud-native applications. The system will provide automated backups, replication across regions, health monitoring, and instant failover capabilities. We are looking for cloud architects, DevOps engineers, and backend developers experienced with AWS, Azure, or GCP. The platform will support multiple cloud providers, implement infrastructure as code, provide RTO/RPO guarantees, and include disaster recovery testing. Features include automated recovery workflows, compliance reporting, and cost optimization. This tool will help businesses ensure business continuity and data protection.',
    domain: 'CLOUD_COMPUTING' as ProjectDomain,
    difficulty: 'EXPERT' as ProjectDifficulty,
    tags: ['Cloud', 'Disaster Recovery', 'DevOps', 'Infrastructure', 'Automation'],
    techStack: ['Terraform', 'Kubernetes', 'Python', 'AWS', 'Azure', 'Prometheus'],
    estimatedDuration: '7-10 months',
    requiredCollaborators: 4,
    requiredSkills: ['Cloud Architecture', 'DevOps', 'Infrastructure as Code', 'Kubernetes', 'Python'],
  },
  {
    title: 'Indie Game Incubator Platform',
    shortDescription: 'Creating a collaborative platform where indie game developers can find team members and resources.',
    fullDescription: 'We are building a platform to connect indie game developers, artists, musicians, and writers to form teams and create amazing games together. The platform will feature project showcases, skill-based matching, collaboration tools, resource sharing, and funding opportunities. We need full-stack developers, game developers, and community managers. Features will include portfolio hosting, team chat, project management tools, asset libraries, and connections to publishers. The platform will also provide educational resources, mentorship programs, and game jams. Let\'s build a thriving indie game development community!',
    domain: 'GAME_DEVELOPMENT' as ProjectDomain,
    difficulty: 'INTERMEDIATE' as ProjectDifficulty,
    tags: ['Gaming', 'Indie', 'Collaboration', 'Community', 'Marketplace'],
    techStack: ['React', 'Node.js', 'PostgreSQL', 'Socket.io', 'AWS S3', 'Redis'],
    estimatedDuration: '5-7 months',
    requiredCollaborators: 4,
    requiredSkills: ['Full-stack Development', 'Game Development', 'UI/UX Design', 'Community Management'],
  },
  {
    title: 'Real-Time Collaborative Code Editor',
    shortDescription: 'Building a web-based IDE with real-time collaboration, AI code completion, and integrated debugging.',
    fullDescription: 'Join us in creating a next-generation collaborative code editor that enables developers to code together in real-time from anywhere. The platform will support multiple programming languages, provide AI-powered code completion, integrated debugging, and version control. We are looking for frontend developers, backend engineers, and DevOps specialists. Features will include syntax highlighting, code execution, terminal access, extensions marketplace, and video chat. The editor will support pair programming, code reviews, and educational use cases. Our goal is to make remote collaboration as seamless as working side-by-side.',
    domain: 'WEB_DEVELOPMENT' as ProjectDomain,
    difficulty: 'ADVANCED' as ProjectDifficulty,
    tags: ['Collaboration', 'IDE', 'Real-time', 'Code Editor', 'Developer Tools'],
    techStack: ['React', 'Monaco Editor', 'WebSocket', 'Node.js', 'Docker', 'Kubernetes'],
    estimatedDuration: '6-9 months',
    requiredCollaborators: 5,
    requiredSkills: ['Frontend Development', 'Backend Development', 'WebSocket', 'DevOps', 'UI/UX'],
  },
  {
    title: 'Fraud Detection System for E-Commerce',
    shortDescription: 'Developing an AI-powered fraud detection system to protect online businesses from payment fraud.',
    fullDescription: 'We are building a sophisticated fraud detection system that uses machine learning to identify and prevent fraudulent transactions in real-time. The system will analyze transaction patterns, user behavior, device fingerprints, and network data to detect anomalies. We need machine learning engineers, data scientists, and backend developers. Features will include risk scoring, automated blocking, manual review queues, and detailed analytics. The system will adapt to new fraud patterns, minimize false positives, and integrate easily with existing e-commerce platforms. Help us protect businesses and consumers from online fraud.',
    domain: 'DATA_SCIENCE' as ProjectDomain,
    difficulty: 'EXPERT' as ProjectDifficulty,
    tags: ['Fraud Detection', 'Machine Learning', 'E-commerce', 'Security', 'Fintech'],
    techStack: ['Python', 'TensorFlow', 'Apache Kafka', 'Redis', 'PostgreSQL', 'FastAPI'],
    estimatedDuration: '7-10 months',
    requiredCollaborators: 4,
    requiredSkills: ['Machine Learning', 'Data Science', 'Backend Development', 'Security', 'Big Data'],
  },
  {
    title: 'Decentralized Identity Management',
    shortDescription: 'Creating a self-sovereign identity system using blockchain for secure, portable digital identities.',
    fullDescription: 'Join our project to build a decentralized identity management system that gives users complete control over their digital identities. The system will use blockchain and cryptographic techniques to create verifiable credentials that can be used across multiple services without central authorities. We need blockchain developers, cryptography experts, and mobile developers. Features will include identity verification, credential issuance, selective disclosure, and revocation mechanisms. The platform will comply with W3C standards and support use cases like KYC, education credentials, and professional certifications. Empower users with true digital identity ownership.',
    domain: 'BLOCKCHAIN' as ProjectDomain,
    difficulty: 'EXPERT' as ProjectDifficulty,
    tags: ['Blockchain', 'Identity', 'Privacy', 'Decentralization', 'Cryptography'],
    techStack: ['Hyperledger Indy', 'React Native', 'Node.js', 'DID', 'Verifiable Credentials'],
    estimatedDuration: '9-12 months',
    requiredCollaborators: 5,
    requiredSkills: ['Blockchain Development', 'Cryptography', 'Mobile Development', 'Security', 'Standards'],
  },
  {
    title: 'AI-Powered Medical Diagnosis Assistant',
    shortDescription: 'Building an AI system to assist doctors in diagnosing diseases from medical images and patient data.',
    fullDescription: 'We are developing an AI-powered diagnostic assistant that helps healthcare professionals make accurate diagnoses faster. The system will analyze medical images (X-rays, CT scans, MRIs), patient symptoms, and medical history to suggest possible diagnoses with confidence scores. We need machine learning engineers, medical professionals, and full-stack developers. The system will be trained on diverse datasets, provide explainable AI insights, and integrate with hospital systems. Features include image annotation tools, case management, and continuous learning from doctor feedback. This project can improve healthcare outcomes and save lives.',
    domain: 'AI_ML' as ProjectDomain,
    difficulty: 'EXPERT' as ProjectDifficulty,
    tags: ['AI', 'Healthcare', 'Medical Imaging', 'Diagnosis', 'Deep Learning'],
    techStack: ['Python', 'PyTorch', 'FastAPI', 'React', 'DICOM', 'PostgreSQL'],
    estimatedDuration: '10-14 months',
    requiredCollaborators: 6,
    requiredSkills: ['Deep Learning', 'Medical Imaging', 'Healthcare IT', 'Full-stack', 'Data Science'],
  },
  {
    title: 'Smart Home Security System',
    shortDescription: 'Developing an affordable, open-source smart home security system with AI-powered threat detection.',
    fullDescription: 'Join us in creating an intelligent home security system that uses IoT devices and AI to protect homes affordably. The system will include smart cameras with facial recognition, motion sensors, door/window sensors, and a central hub. We need IoT developers, AI engineers, and mobile developers. Features will include real-time alerts, video recording, two-way audio, automated responses, and integration with smart locks. The AI will distinguish between family members, pets, and intruders, reducing false alarms. The system will be privacy-focused with local processing and encrypted cloud backup. Make home security accessible to everyone.',
    domain: 'IOT' as ProjectDomain,
    difficulty: 'ADVANCED' as ProjectDifficulty,
    tags: ['IoT', 'Security', 'Smart Home', 'AI', 'Computer Vision'],
    techStack: ['Raspberry Pi', 'Python', 'TensorFlow', 'React Native', 'MQTT', 'WebRTC'],
    estimatedDuration: '6-9 months',
    requiredCollaborators: 5,
    requiredSkills: ['IoT Development', 'Computer Vision', 'Mobile Development', 'Embedded Systems', 'AI'],
  },
  {
    title: 'Penetration Testing Automation Framework',
    shortDescription: 'Building an automated penetration testing framework for continuous security assessment.',
    fullDescription: 'We are creating a comprehensive penetration testing framework that automates security assessments for web applications, networks, and cloud infrastructure. The framework will perform reconnaissance, vulnerability scanning, exploitation, and reporting automatically. We need security researchers, Python developers, and DevOps engineers. Features will include custom exploit modules, integration with CI/CD pipelines, compliance checking, and detailed remediation guidance. The framework will support scheduling, parallel testing, and API access. This tool will help organizations maintain continuous security posture and comply with regulations.',
    domain: 'CYBERSECURITY' as ProjectDomain,
    difficulty: 'EXPERT' as ProjectDifficulty,
    tags: ['Penetration Testing', 'Security', 'Automation', 'DevSecOps', 'Vulnerability'],
    techStack: ['Python', 'Metasploit', 'Docker', 'Kubernetes', 'PostgreSQL', 'React'],
    estimatedDuration: '7-10 months',
    requiredCollaborators: 4,
    requiredSkills: ['Penetration Testing', 'Python', 'Security Research', 'DevOps', 'Networking'],
  },
  {
    title: 'Serverless Data Pipeline Platform',
    shortDescription: 'Creating a visual ETL platform for building serverless data pipelines with no-code interface.',
    fullDescription: 'Join our team to build a user-friendly platform for creating and managing serverless data pipelines. The platform will provide a drag-and-drop interface for designing ETL workflows, support multiple data sources and destinations, and handle data transformation at scale. We need cloud engineers, backend developers, and frontend developers. Features will include pre-built connectors, custom transformations, scheduling, monitoring, and cost optimization. The platform will be cloud-agnostic, support real-time and batch processing, and provide data quality checks. Democratize data engineering for analysts and business users.',
    domain: 'CLOUD_COMPUTING' as ProjectDomain,
    difficulty: 'ADVANCED' as ProjectDifficulty,
    tags: ['Cloud', 'ETL', 'Data Pipeline', 'Serverless', 'No-Code'],
    techStack: ['AWS Lambda', 'React', 'Node.js', 'Apache Airflow', 'Terraform', 'PostgreSQL'],
    estimatedDuration: '6-9 months',
    requiredCollaborators: 5,
    requiredSkills: ['Cloud Architecture', 'Backend Development', 'Frontend Development', 'Data Engineering', 'DevOps'],
  },
  {
    title: 'Multiplayer Strategy Game',
    shortDescription: 'Developing a turn-based strategy game with deep gameplay mechanics and competitive multiplayer.',
    fullDescription: 'We are creating an engaging turn-based strategy game that combines resource management, tactical combat, and diplomacy. The game will feature multiple civilizations, tech trees, unit customization, and various victory conditions. We need game developers, 3D artists, sound designers, and backend engineers. Features will include single-player campaigns, ranked multiplayer, tournaments, replay system, and mod support. The game will have cross-platform play, spectator mode, and regular content updates. Join us to create a strategy game that rivals the classics while bringing fresh innovations to the genre.',
    domain: 'GAME_DEVELOPMENT' as ProjectDomain,
    difficulty: 'ADVANCED' as ProjectDifficulty,
    tags: ['Gaming', 'Strategy', 'Multiplayer', 'Turn-based', 'Competitive'],
    techStack: ['Unity', 'C#', 'Photon', 'PostgreSQL', 'Node.js', 'Blender'],
    estimatedDuration: '10-15 months',
    requiredCollaborators: 6,
    requiredSkills: ['Game Development', 'Unity', '3D Modeling', 'Backend Development', 'Game Design'],
  },
  {
    title: 'Predictive Analytics for Retail',
    shortDescription: 'Building a machine learning platform for retail demand forecasting and inventory optimization.',
    fullDescription: 'Join us in developing a predictive analytics platform that helps retailers optimize inventory, reduce waste, and maximize profits. The system will forecast demand using historical sales, seasonality, promotions, and external factors like weather and events. We need data scientists, machine learning engineers, and full-stack developers. Features will include automated reordering, price optimization, markdown recommendations, and supplier management. The platform will provide intuitive dashboards, what-if scenarios, and integration with POS and ERP systems. Help retailers make data-driven decisions and improve their bottom line.',
    domain: 'DATA_SCIENCE' as ProjectDomain,
    difficulty: 'ADVANCED' as ProjectDifficulty,
    tags: ['Predictive Analytics', 'Retail', 'Machine Learning', 'Inventory', 'Forecasting'],
    techStack: ['Python', 'Scikit-learn', 'Prophet', 'React', 'PostgreSQL', 'Apache Spark'],
    estimatedDuration: '6-8 months',
    requiredCollaborators: 4,
    requiredSkills: ['Data Science', 'Machine Learning', 'Full-stack Development', 'Statistics', 'Business Analytics'],
  },
  {
    title: 'Language Learning Social Network',
    shortDescription: 'Creating a social platform that connects language learners with native speakers for practice and cultural exchange.',
    fullDescription: 'We are building a vibrant community platform where people can learn languages through conversation with native speakers. The platform will match learners based on languages, interests, and availability, provide video/voice chat, and include learning resources. We need full-stack developers, mobile developers, and UX designers. Features will include structured lessons, vocabulary tracking, pronunciation feedback using AI, cultural exchange forums, and gamification. The platform will support 50+ languages, offer both free and premium tiers, and include safety features for user protection. Make language learning social and fun!',
    domain: 'MOBILE_DEVELOPMENT' as ProjectDomain,
    difficulty: 'INTERMEDIATE' as ProjectDifficulty,
    tags: ['Education', 'Language Learning', 'Social Network', 'Mobile', 'Community'],
    techStack: ['React Native', 'Node.js', 'MongoDB', 'WebRTC', 'Firebase', 'TensorFlow Lite'],
    estimatedDuration: '5-7 months',
    requiredCollaborators: 4,
    requiredSkills: ['Mobile Development', 'Backend Development', 'UI/UX Design', 'WebRTC', 'Community Management'],
  },
  {
    title: 'Quantum Computing Simulator',
    shortDescription: 'Developing an educational quantum computing simulator with visual circuit design and algorithm library.',
    fullDescription: 'Join our project to create an accessible quantum computing simulator that helps students and researchers learn quantum algorithms. The simulator will provide a visual circuit designer, support major quantum gates, and include implementations of famous algorithms like Shor\'s and Grover\'s. We need quantum computing experts, software developers, and educators. Features will include step-by-step execution, state visualization, noise simulation, and educational tutorials. The platform will support exporting to real quantum hardware APIs and include a community library of circuits. Make quantum computing education accessible to everyone.',
    domain: 'WEB_DEVELOPMENT' as ProjectDomain,
    difficulty: 'EXPERT' as ProjectDifficulty,
    tags: ['Quantum Computing', 'Education', 'Simulation', 'Physics', 'Algorithms'],
    techStack: ['React', 'Python', 'Qiskit', 'NumPy', 'WebAssembly', 'Three.js'],
    estimatedDuration: '7-10 months',
    requiredCollaborators: 4,
    requiredSkills: ['Quantum Computing', 'Full-stack Development', 'Physics', 'Mathematics', 'Education'],
  },
  {
    title: 'NFT Marketplace for Digital Art',
    shortDescription: 'Building a user-friendly NFT marketplace focused on supporting digital artists and creators.',
    fullDescription: 'We are creating an NFT marketplace that empowers digital artists to mint, sell, and trade their artwork with low fees and excellent user experience. The platform will support multiple blockchains, provide creator royalties, and include social features for artist promotion. We need blockchain developers, frontend developers, and designers. Features will include lazy minting, auction mechanisms, collection management, rarity tools, and integrated wallet. The marketplace will emphasize sustainability with eco-friendly blockchain options and provide analytics for creators. Help us build a fair, artist-first NFT ecosystem.',
    domain: 'BLOCKCHAIN' as ProjectDomain,
    difficulty: 'ADVANCED' as ProjectDifficulty,
    tags: ['NFT', 'Blockchain', 'Digital Art', 'Marketplace', 'Web3'],
    techStack: ['Solidity', 'React', 'Ethers.js', 'IPFS', 'Node.js', 'MongoDB'],
    estimatedDuration: '6-9 months',
    requiredCollaborators: 5,
    requiredSkills: ['Blockchain Development', 'Smart Contracts', 'Frontend Development', 'UI/UX Design', 'Web3'],
  },
  {
    title: 'Telemedicine Platform for Rural Areas',
    shortDescription: 'Developing a telemedicine solution to bring healthcare access to underserved rural communities.',
    fullDescription: 'Join us in building a telemedicine platform specifically designed for rural areas with limited internet connectivity. The platform will work on low bandwidth, support offline consultations, and include features for remote diagnosis. We need healthcare IT specialists, mobile developers, and backend engineers. Features will include video consultations, prescription management, health records, appointment scheduling, and integration with local pharmacies. The platform will support multiple languages, provide health education content, and enable community health workers. This project can dramatically improve healthcare access for millions.',
    domain: 'MOBILE_DEVELOPMENT' as ProjectDomain,
    difficulty: 'ADVANCED' as ProjectDifficulty,
    tags: ['Healthcare', 'Telemedicine', 'Social Impact', 'Rural', 'Mobile'],
    techStack: ['Flutter', 'Node.js', 'PostgreSQL', 'WebRTC', 'Firebase', 'Offline-first'],
    estimatedDuration: '7-10 months',
    requiredCollaborators: 5,
    requiredSkills: ['Mobile Development', 'Healthcare IT', 'Backend Development', 'Offline-first', 'UI/UX'],
  },
  {
    title: 'Container Security Scanner',
    shortDescription: 'Creating an automated security scanner for Docker containers and Kubernetes clusters.',
    fullDescription: 'We are building a comprehensive security scanner that identifies vulnerabilities in container images and Kubernetes configurations. The tool will scan for CVEs, misconfigurations, secrets, and compliance violations. We need security engineers, DevOps specialists, and backend developers. Features will include CI/CD integration, policy enforcement, automated remediation suggestions, and detailed reporting. The scanner will support multiple registries, provide risk scoring, and track vulnerabilities over time. Integration with popular DevOps tools and support for custom security policies. Help organizations secure their containerized applications.',
    domain: 'CYBERSECURITY' as ProjectDomain,
    difficulty: 'ADVANCED' as ProjectDifficulty,
    tags: ['Security', 'Containers', 'Kubernetes', 'DevSecOps', 'Vulnerability'],
    techStack: ['Go', 'Docker', 'Kubernetes', 'PostgreSQL', 'React', 'Trivy'],
    estimatedDuration: '5-7 months',
    requiredCollaborators: 4,
    requiredSkills: ['Cybersecurity', 'Kubernetes', 'DevOps', 'Go', 'Container Security'],
  },
  {
    title: 'Smart Waste Management System',
    shortDescription: 'Building an IoT solution for optimizing waste collection routes and promoting recycling in cities.',
    fullDescription: 'Join our project to create a smart waste management system that makes cities cleaner and more sustainable. The system will use IoT sensors in bins to monitor fill levels, optimize collection routes, and reduce operational costs. We need IoT engineers, data scientists, and mobile developers. Features will include route optimization algorithms, citizen reporting app, recycling education, and analytics dashboard for city officials. The system will predict waste generation patterns, identify illegal dumping, and gamify recycling participation. Help us create cleaner, more sustainable cities.',
    domain: 'IOT' as ProjectDomain,
    difficulty: 'INTERMEDIATE' as ProjectDifficulty,
    tags: ['IoT', 'Smart City', 'Sustainability', 'Waste Management', 'Environment'],
    techStack: ['Arduino', 'Python', 'React Native', 'MQTT', 'PostgreSQL', 'Google Maps API'],
    estimatedDuration: '5-7 months',
    requiredCollaborators: 4,
    requiredSkills: ['IoT Development', 'Mobile Development', 'Data Science', 'Backend Development', 'GIS'],
  },
  {
    title: 'Multi-Cloud Cost Dashboard',
    shortDescription: 'Developing a unified dashboard for monitoring and optimizing costs across AWS, Azure, and GCP.',
    fullDescription: 'We are creating a comprehensive cost management dashboard that provides visibility into spending across multiple cloud providers. The platform will aggregate billing data, identify cost anomalies, recommend optimizations, and forecast future spending. We need cloud engineers, full-stack developers, and data visualization experts. Features will include custom alerts, budget tracking, resource tagging, showback/chargeback, and automated cost-saving actions. The dashboard will provide actionable insights, support custom reports, and integrate with financial systems. Help organizations control their cloud spending and maximize ROI.',
    domain: 'CLOUD_COMPUTING' as ProjectDomain,
    difficulty: 'ADVANCED' as ProjectDifficulty,
    tags: ['Cloud', 'Cost Management', 'FinOps', 'Multi-Cloud', 'Analytics'],
    techStack: ['Python', 'React', 'AWS SDK', 'Azure SDK', 'GCP SDK', 'PostgreSQL', 'Grafana'],
    estimatedDuration: '6-8 months',
    requiredCollaborators: 4,
    requiredSkills: ['Cloud Architecture', 'Full-stack Development', 'Data Visualization', 'FinOps', 'APIs'],
  },
];

async function main() {
  console.log('Starting to seed community posts...');

  // Get or create a default user for posts
  let user = await prisma.user.findFirst();
  
  if (!user) {
    console.log('No users found. Creating a default user...');
    user = await prisma.user.create({
      data: {
        email: 'community@devmatch.com',
        name: 'DevMatch Community',
        username: 'devmatch_community',
        bio: 'Official DevMatch community account for seeding projects',
        skills: ['Full-stack', 'AI', 'Blockchain', 'IoT', 'Cloud'],
        interests: ['Innovation', 'Open Source', 'Collaboration'],
        onboardingCompleted: true,
      },
    });
  }

  console.log(`Using user: ${user.name} (${user.email})`);

  // Create IDEA posts
  console.log('\nCreating 25 IDEA posts...');
  for (let i = 0; i < IDEAS.length; i++) {
    const idea = IDEAS[i];
    try {
      const post = await prisma.communityPost.create({
        data: {
          type: 'IDEA' as PostType,
          title: idea.title,
          slug: idea.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') + `-${Date.now()}-${i}`,
          shortDescription: idea.shortDescription,
          fullDescription: idea.fullDescription,
          domain: idea.domain,
          difficulty: idea.difficulty,
          tags: idea.tags,
          techStack: idea.techStack,
          estimatedDuration: idea.estimatedDuration,
          authorId: user.id,
          isAnonymous: false,
          viewCount: Math.floor(Math.random() * 500) + 50,
          status: 'ACTIVE',
        },
      });
      console.log(`✓ Created IDEA: ${post.title}`);
    } catch (error) {
      console.error(`✗ Failed to create IDEA: ${idea.title}`, error);
    }
  }

  // Create COLLABORATION posts
  console.log('\nCreating 25 COLLABORATION posts...');
  for (let i = 0; i < COLLABORATIONS.length; i++) {
    const collab = COLLABORATIONS[i];
    try {
      const post = await prisma.communityPost.create({
        data: {
          type: 'COLLABORATION' as PostType,
          title: collab.title,
          slug: collab.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') + `-${Date.now()}-${i}`,
          shortDescription: collab.shortDescription,
          fullDescription: collab.fullDescription,
          domain: collab.domain,
          difficulty: collab.difficulty,
          tags: collab.tags,
          techStack: collab.techStack,
          estimatedDuration: collab.estimatedDuration,
          requiredCollaborators: collab.requiredCollaborators,
          requiredSkills: collab.requiredSkills,
          authorId: user.id,
          isAnonymous: false,
          viewCount: Math.floor(Math.random() * 500) + 50,
          status: 'ACTIVE',
        },
      });
      console.log(`✓ Created COLLABORATION: ${post.title}`);
    } catch (error) {
      console.error(`✗ Failed to create COLLABORATION: ${collab.title}`, error);
    }
  }

  console.log('\n✅ Seeding completed successfully!');
  console.log(`Total posts created: ${IDEAS.length + COLLABORATIONS.length}`);
}

main()
  .catch((e) => {
    console.error('Error seeding database:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
