import type { ProjectDetail } from './project.types';

export const fallbackProjects: ProjectDetail[] = [
  {
    id: 'fallback-1',
    slug: 'ai-resume-analyzer',
    title: 'AI-Powered Resume Analyzer',
    description: 'Intelligent system that analyzes resumes using NLP and provides actionable feedback',
    longDescription: 'Create a comprehensive resume analysis platform using NLP and ML to evaluate resumes against job descriptions. Provides feedback on content quality, keyword optimization, and ATS compatibility.',
    domain: 'MACHINE_LEARNING',
    difficulty: 'INTERMEDIATE',
    estimatedHours: 240,
    techStack: ['Python', 'FastAPI', 'spaCy', 'React', 'TypeScript', 'PostgreSQL', 'Redis'],
    features: ['PDF/DOCX parsing', 'ATS compatibility scoring', 'Keyword optimization', 'Skills gap analysis', 'Grammar checking', 'Visual analytics', 'PDF reports'],
    learningOutcomes: ['Implement NLP pipelines', 'Build ML classification models', 'Design microservices', 'Handle async processing', 'Deploy ML models'],
    prerequisites: ['Python & FastAPI', 'NLP fundamentals', 'Machine Learning basics', 'React development', 'RESTful APIs'],
    tags: ['AI', 'NLP', 'Machine Learning', 'Python', 'React'],
    createdAt: new Date('2024-01-01')
  },
  {
    id: 'fallback-2',
    slug: 'real-time-code-editor',
    title: 'Real-Time Collaborative Code Editor',
    description: 'Web-based code editor with real-time collaboration and live execution',
    longDescription: 'Build a sophisticated online code editor enabling multiple users to write and execute code simultaneously. Features WebSocket synchronization, syntax highlighting, and sandboxed execution.',
    domain: 'WEB_DEVELOPMENT',
    difficulty: 'ADVANCED',
    estimatedHours: 400,
    techStack: ['Next.js', 'TypeScript', 'Monaco Editor', 'Socket.io', 'Node.js', 'Docker', 'MongoDB', 'Redis'],
    features: ['Real-time collaboration', 'Syntax highlighting', 'Live code execution', 'Version control', 'Video calling', 'Room sharing', 'Auto-save'],
    learningOutcomes: ['Implement real-time collaboration', 'Build WebSocket infrastructure', 'Design secure execution environments', 'Handle concurrent editing', 'Deploy microservices'],
    prerequisites: ['Advanced JavaScript', 'WebSocket protocols', 'Docker orchestration', 'Operational transformation', 'System design'],
    tags: ['Web Development', 'Real-time', 'WebSocket', 'Collaboration', 'Next.js'],
    createdAt: new Date('2024-01-02')
  },
  {
    id: 'fallback-3',
    slug: 'ecommerce-platform',
    title: 'Full-Stack E-Commerce Platform',
    description: 'Complete online store with payment integration, inventory management, and admin dashboard',
    longDescription: 'Build a production-ready e-commerce platform with product catalog, shopping cart, payment processing, order management, and comprehensive admin panel.',
    domain: 'WEB_DEVELOPMENT',
    difficulty: 'INTERMEDIATE',
    estimatedHours: 320,
    techStack: ['React', 'Redux', 'Tailwind CSS', 'Node.js', 'Express', 'Stripe', 'PostgreSQL', 'AWS S3'],
    features: ['Product catalog', 'Shopping cart', 'Payment processing', 'Order tracking', 'Inventory management', 'Admin dashboard', 'Email notifications'],
    learningOutcomes: ['Build complete web applications', 'Integrate payment gateways', 'Design database schemas', 'Implement authentication', 'Deploy production apps'],
    prerequisites: ['Full-stack development', 'Payment integration', 'Database design', 'State management', 'Authentication'],
    tags: ['E-commerce', 'Full-stack', 'React', 'Node.js', 'Stripe'],
    createdAt: new Date('2024-01-03')
  },
  {
    id: 'fallback-4',
    slug: 'fitness-tracking-app',
    title: 'Fitness Tracking Mobile App',
    description: 'Cross-platform fitness app with workout tracking, nutrition logging, and progress analytics',
    longDescription: 'Build a comprehensive fitness application using React Native that tracks workouts, monitors nutrition, provides exercise guides, and visualizes progress over time.',
    domain: 'MOBILE_DEVELOPMENT',
    difficulty: 'INTERMEDIATE',
    estimatedHours: 280,
    techStack: ['React Native', 'Expo', 'Node.js', 'Express', 'MongoDB', 'Firebase', 'Chart.js'],
    features: ['Workout logging', 'Nutrition tracking', 'Exercise library', 'Progress charts', 'Goal setting', 'Social sharing', 'Push notifications'],
    learningOutcomes: ['Build cross-platform apps', 'Implement offline functionality', 'Handle device sensors', 'Create data visualizations', 'Deploy mobile apps'],
    prerequisites: ['React Native', 'Mobile UI/UX', 'REST APIs', 'Local storage', 'Push notifications'],
    tags: ['Mobile', 'React Native', 'Fitness', 'Health', 'Firebase'],
    createdAt: new Date('2024-01-04')
  },
  {
    id: 'fallback-5',
    slug: 'iot-smart-home-system',
    title: 'IoT Smart Home Automation',
    description: 'Complete smart home system with sensor integration and mobile control',
    longDescription: 'Create an IoT-based smart home automation system that controls lights, temperature, security, and appliances through a mobile app and voice commands.',
    domain: 'IOT',
    difficulty: 'ADVANCED',
    estimatedHours: 400,
    techStack: ['Python', 'MQTT', 'Flask', 'React Native', 'InfluxDB', 'Raspberry Pi', 'Arduino', 'AWS IoT'],
    features: ['Device control', 'Sensor monitoring', 'Automation rules', 'Voice commands', 'Energy monitoring', 'Security alerts', 'Remote access'],
    learningOutcomes: ['Build IoT systems', 'Work with sensors', 'Implement MQTT', 'Create automation rules', 'Deploy edge computing'],
    prerequisites: ['IoT protocols', 'Embedded systems', 'MQTT messaging', 'Mobile development', 'Hardware integration'],
    tags: ['IoT', 'Smart Home', 'Automation', 'Raspberry Pi', 'MQTT'],
    createdAt: new Date('2024-01-05')
  },
  {
    id: 'fallback-6',
    slug: 'blockchain-voting-system',
    title: 'Blockchain-Based Voting Platform',
    description: 'Secure and transparent voting system using blockchain technology',
    longDescription: 'Create a decentralized voting platform using blockchain to ensure transparency, security, and immutability of votes. Features voter authentication and real-time results.',
    domain: 'BLOCKCHAIN',
    difficulty: 'ADVANCED',
    estimatedHours: 400,
    techStack: ['Solidity', 'Hardhat', 'React', 'Web3.js', 'Ethereum', 'IPFS', 'MetaMask'],
    features: ['Voter registration', 'Secure voting', 'Real-time results', 'Vote verification', 'Candidate management', 'Audit trail', 'Anonymous voting'],
    learningOutcomes: ['Develop smart contracts', 'Build dApps', 'Implement blockchain security', 'Work with Web3', 'Deploy on Ethereum'],
    prerequisites: ['Blockchain fundamentals', 'Solidity programming', 'Smart contracts', 'Web3 integration', 'Cryptography basics'],
    tags: ['Blockchain', 'Ethereum', 'Smart Contracts', 'Voting', 'Web3'],
    createdAt: new Date('2024-01-06')
  },
  {
    id: 'fallback-7',
    slug: 'intrusion-detection-system',
    title: 'Network Intrusion Detection System',
    description: 'ML-based system for detecting and preventing network security threats',
    longDescription: 'Build a cybersecurity system that monitors network traffic, detects anomalies, identifies potential threats, and provides real-time alerts using machine learning.',
    domain: 'CYBERSECURITY',
    difficulty: 'ADVANCED',
    estimatedHours: 360,
    techStack: ['Python', 'Scapy', 'TensorFlow', 'React', 'D3.js', 'Elasticsearch', 'Wireshark', 'Docker'],
    features: ['Packet analysis', 'Anomaly detection', 'Threat classification', 'Real-time alerts', 'Traffic visualization', 'Incident logging', 'Report generation'],
    learningOutcomes: ['Analyze network traffic', 'Build ML detectors', 'Implement security monitoring', 'Handle real-time data', 'Create security dashboards'],
    prerequisites: ['Network security', 'Packet analysis', 'Machine learning', 'Python programming', 'Security protocols'],
    tags: ['Cybersecurity', 'Machine Learning', 'Network Security', 'Python', 'IDS'],
    createdAt: new Date('2024-01-07')
  },
  {
    id: 'fallback-8',
    slug: 'cloud-file-storage',
    title: 'Distributed Cloud Storage System',
    description: 'Scalable file storage system with encryption and distributed architecture',
    longDescription: 'Create a cloud storage platform similar to Dropbox with file upload, sharing, versioning, and distributed storage across multiple nodes for redundancy.',
    domain: 'CLOUD_COMPUTING',
    difficulty: 'ADVANCED',
    estimatedHours: 480,
    techStack: ['Go', 'gRPC', 'React', 'PostgreSQL', 'MinIO', 'Kubernetes', 'Docker', 'Redis'],
    features: ['File upload/download', 'Folder management', 'File sharing', 'Version control', 'Encryption', 'Deduplication', 'Distributed storage'],
    learningOutcomes: ['Build distributed systems', 'Implement file storage', 'Use Kubernetes', 'Handle large files', 'Design scalable architecture'],
    prerequisites: ['Distributed systems', 'Go programming', 'Microservices', 'Kubernetes', 'Storage systems'],
    tags: ['Cloud Computing', 'Distributed Systems', 'Storage', 'Go', 'Kubernetes'],
    createdAt: new Date('2024-01-08')
  },
  {
    id: 'fallback-9',
    slug: 'sales-forecasting-dashboard',
    title: 'Sales Forecasting Analytics Platform',
    description: 'Data science project for predicting sales trends using time series analysis',
    longDescription: 'Build a comprehensive sales forecasting system using time series models, featuring interactive dashboards, trend analysis, and automated reporting.',
    domain: 'DATA_SCIENCE',
    difficulty: 'INTERMEDIATE',
    estimatedHours: 280,
    techStack: ['Python', 'Prophet', 'Pandas', 'Streamlit', 'Plotly', 'PostgreSQL', 'Jupyter', 'Docker'],
    features: ['Time series forecasting', 'Trend analysis', 'Seasonality detection', 'Interactive dashboards', 'Automated reports', 'What-if scenarios'],
    learningOutcomes: ['Implement forecasting models', 'Analyze time series data', 'Build interactive dashboards', 'Handle business metrics', 'Deploy data apps'],
    prerequisites: ['Time series analysis', 'Python data science stack', 'Statistical modeling', 'Data visualization', 'Dashboard development'],
    tags: ['Data Science', 'Time Series', 'Forecasting', 'Python', 'Analytics'],
    createdAt: new Date('2024-01-09')
  },
  {
    id: 'fallback-10',
    slug: 'recommendation-engine',
    title: 'Personalized Recommendation Engine',
    description: 'ML-based recommendation system using collaborative and content-based filtering',
    longDescription: 'Create a sophisticated recommendation engine that combines collaborative filtering, content-based filtering, and hybrid approaches to provide personalized recommendations.',
    domain: 'DATA_SCIENCE',
    difficulty: 'ADVANCED',
    estimatedHours: 360,
    techStack: ['Python', 'FastAPI', 'Surprise', 'React', 'PostgreSQL', 'Redis', 'Docker', 'Celery'],
    features: ['Collaborative filtering', 'Content-based filtering', 'Hybrid recommendations', 'Real-time updates', 'A/B testing', 'Performance metrics'],
    learningOutcomes: ['Build recommendation systems', 'Implement filtering algorithms', 'Handle sparse matrices', 'Optimize recommendations', 'Evaluate recommenders'],
    prerequisites: ['Recommendation algorithms', 'Matrix factorization', 'Python ML libraries', 'API development', 'Performance optimization'],
    tags: ['Data Science', 'Machine Learning', 'Recommendations', 'Python', 'FastAPI'],
    createdAt: new Date('2024-01-10')
  },
  {
    id: 'fallback-11',
    slug: 'hospital-management-system',
    title: 'Hospital Management System',
    description: 'Comprehensive hospital management platform with patient records, appointments, and billing',
    longDescription: 'Build a complete hospital management system that handles patient registration, appointment scheduling, electronic health records (EHR), billing, pharmacy management, and staff coordination. Features role-based access control, real-time notifications, and comprehensive reporting.',
    domain: 'WEB_DEVELOPMENT',
    difficulty: 'ADVANCED',
    estimatedHours: 450,
    techStack: ['Java', 'Spring Boot', 'React', 'PostgreSQL', 'Redis', 'Apache Kafka', 'Docker', 'JWT'],
    features: ['Patient registration', 'Appointment scheduling', 'EHR management', 'Billing system', 'Pharmacy integration', 'Lab reports', 'Staff management', 'Insurance claims', 'Real-time notifications', 'Audit logs'],
    learningOutcomes: ['Build enterprise applications', 'Implement RBAC', 'Design complex databases', 'Handle HIPAA compliance', 'Deploy microservices architecture', 'Implement event-driven systems'],
    prerequisites: ['Java & Spring Boot', 'Enterprise architecture', 'Database design', 'Security best practices', 'Healthcare domain knowledge'],
    tags: ['Healthcare', 'Enterprise', 'Java', 'Spring Boot', 'Microservices'],
    createdAt: new Date('2024-01-11')
  },
  {
    id: 'fallback-12',
    slug: 'stock-trading-bot',
    title: 'Algorithmic Stock Trading Bot',
    description: 'Automated trading system with technical analysis and backtesting capabilities',
    longDescription: 'Create an intelligent stock trading bot that uses technical indicators, machine learning models, and sentiment analysis to make automated trading decisions. Includes comprehensive backtesting, risk management, and real-time market data integration.',
    domain: 'DATA_SCIENCE',
    difficulty: 'ADVANCED',
    estimatedHours: 400,
    techStack: ['Python', 'Pandas', 'NumPy', 'scikit-learn', 'TA-Lib', 'Alpaca API', 'PostgreSQL', 'Celery', 'Redis', 'Streamlit'],
    features: ['Technical analysis', 'ML predictions', 'Sentiment analysis', 'Backtesting engine', 'Risk management', 'Portfolio optimization', 'Real-time trading', 'Performance analytics', 'Alert system', 'Paper trading'],
    learningOutcomes: ['Implement trading strategies', 'Build backtesting frameworks', 'Apply ML to finance', 'Handle real-time data', 'Manage trading risks', 'Optimize portfolios'],
    prerequisites: ['Python data science', 'Financial markets', 'Technical analysis', 'Machine learning', 'Time series analysis', 'API integration'],
    tags: ['Finance', 'Trading', 'Machine Learning', 'Python', 'Algorithmic Trading'],
    createdAt: new Date('2024-01-12')
  },
  {
    id: 'fallback-13',
    slug: 'video-streaming-platform',
    title: 'Video Streaming Platform',
    description: 'Netflix-like video streaming service with adaptive bitrate and content delivery',
    longDescription: 'Build a scalable video streaming platform similar to Netflix with features like adaptive bitrate streaming, content recommendations, user profiles, watch history, and content management. Implements HLS/DASH protocols and CDN integration for optimal delivery.',
    domain: 'WEB_DEVELOPMENT',
    difficulty: 'ADVANCED',
    estimatedHours: 480,
    techStack: ['Next.js', 'TypeScript', 'Node.js', 'FFmpeg', 'AWS S3', 'CloudFront', 'MongoDB', 'Redis', 'Elasticsearch', 'Socket.io'],
    features: ['Video upload & transcoding', 'Adaptive streaming', 'Content recommendations', 'User profiles', 'Watch history', 'Subtitles support', 'Offline downloads', 'Parental controls', 'Search functionality', 'Analytics dashboard'],
    learningOutcomes: ['Implement video streaming', 'Build CDN integration', 'Handle large file uploads', 'Design scalable architecture', 'Optimize video delivery', 'Implement recommendation systems'],
    prerequisites: ['Full-stack development', 'Video encoding', 'CDN concepts', 'Streaming protocols', 'Cloud services', 'Database optimization'],
    tags: ['Streaming', 'Video', 'Next.js', 'AWS', 'CDN'],
    createdAt: new Date('2024-01-13')
  },
  {
    id: 'fallback-14',
    slug: 'restaurant-pos-system',
    title: 'Restaurant POS & Management System',
    description: 'Complete point-of-sale system with inventory, kitchen display, and analytics',
    longDescription: 'Develop a comprehensive restaurant management system with POS functionality, kitchen display system (KDS), inventory management, table reservations, staff scheduling, and detailed analytics. Supports multiple payment methods and integrates with delivery platforms.',
    domain: 'WEB_DEVELOPMENT',
    difficulty: 'INTERMEDIATE',
    estimatedHours: 350,
    techStack: ['React', 'Node.js', 'Express', 'MongoDB', 'Socket.io', 'Stripe', 'Twilio', 'Chart.js', 'PWA'],
    features: ['Order management', 'Kitchen display', 'Inventory tracking', 'Table management', 'Staff scheduling', 'Payment processing', 'Receipt printing', 'Customer loyalty', 'Delivery integration', 'Sales analytics'],
    learningOutcomes: ['Build real-time systems', 'Implement POS logic', 'Handle concurrent orders', 'Design offline-first apps', 'Integrate payment gateways', 'Create PWAs'],
    prerequisites: ['Full-stack JavaScript', 'Real-time communication', 'Payment integration', 'PWA development', 'Restaurant operations'],
    tags: ['POS', 'Restaurant', 'Real-time', 'React', 'Node.js'],
    createdAt: new Date('2024-01-14')
  },
  {
    id: 'fallback-15',
    slug: 'ai-chatbot-platform',
    title: 'AI-Powered Customer Service Chatbot',
    description: 'Intelligent chatbot with NLP, multi-language support, and CRM integration',
    longDescription: 'Create an advanced AI chatbot platform for customer service that uses natural language processing, intent recognition, and context management. Features multi-language support, sentiment analysis, human handoff, and integration with popular CRM systems.',
    domain: 'MACHINE_LEARNING',
    difficulty: 'ADVANCED',
    estimatedHours: 420,
    techStack: ['Python', 'Rasa', 'FastAPI', 'React', 'PostgreSQL', 'Redis', 'Elasticsearch', 'Docker', 'Kubernetes'],
    features: ['Intent recognition', 'Entity extraction', 'Context management', 'Multi-language support', 'Sentiment analysis', 'Human handoff', 'CRM integration', 'Analytics dashboard', 'Training interface', 'API webhooks'],
    learningOutcomes: ['Build conversational AI', 'Implement NLP pipelines', 'Design dialogue management', 'Handle multi-turn conversations', 'Deploy ML models', 'Scale chatbot systems'],
    prerequisites: ['NLP fundamentals', 'Python ML stack', 'Dialogue systems', 'API development', 'Microservices', 'Kubernetes basics'],
    tags: ['AI', 'Chatbot', 'NLP', 'Python', 'Rasa'],
    createdAt: new Date('2024-01-15')
  },
  {
    id: 'fallback-16',
    slug: 'social-media-analytics',
    title: 'Social Media Analytics Dashboard',
    description: 'Comprehensive analytics platform for tracking social media metrics and engagement',
    longDescription: 'Build a powerful social media analytics platform that aggregates data from multiple platforms (Twitter, Instagram, Facebook, LinkedIn), provides sentiment analysis, tracks engagement metrics, identifies trends, and generates automated reports with actionable insights.',
    domain: 'DATA_SCIENCE',
    difficulty: 'INTERMEDIATE',
    estimatedHours: 320,
    techStack: ['Python', 'Django', 'React', 'PostgreSQL', 'Celery', 'Redis', 'Plotly', 'Twitter API', 'Facebook Graph API'],
    features: ['Multi-platform integration', 'Sentiment analysis', 'Engagement tracking', 'Trend identification', 'Competitor analysis', 'Automated reports', 'Custom dashboards', 'Influencer detection', 'Hashtag analytics', 'Export functionality'],
    learningOutcomes: ['Integrate social APIs', 'Implement sentiment analysis', 'Build data pipelines', 'Create interactive dashboards', 'Handle rate limiting', 'Design analytics systems'],
    prerequisites: ['Python & Django', 'Data analysis', 'API integration', 'Data visualization', 'Social media platforms', 'NLP basics'],
    tags: ['Analytics', 'Social Media', 'Python', 'Django', 'Data Science'],
    createdAt: new Date('2024-01-16')
  },
  {
    id: 'fallback-17',
    slug: 'online-exam-proctoring',
    title: 'AI-Based Online Exam Proctoring System',
    description: 'Automated exam monitoring with face detection, eye tracking, and anomaly detection',
    longDescription: 'Develop an AI-powered online examination platform with automated proctoring capabilities including face detection, eye tracking, tab switching detection, multiple person detection, and audio monitoring. Features secure browser mode, question randomization, and detailed violation reports.',
    domain: 'MACHINE_LEARNING',
    difficulty: 'ADVANCED',
    estimatedHours: 400,
    techStack: ['Python', 'TensorFlow', 'OpenCV', 'FastAPI', 'React', 'WebRTC', 'PostgreSQL', 'Redis', 'AWS S3'],
    features: ['Face detection', 'Eye tracking', 'Tab monitoring', 'Audio analysis', 'Screen recording', 'Question bank', 'Auto-grading', 'Violation alerts', 'Secure browser', 'Detailed reports'],
    learningOutcomes: ['Implement computer vision', 'Build real-time monitoring', 'Handle video streams', 'Design secure systems', 'Deploy ML models', 'Create exam platforms'],
    prerequisites: ['Computer vision', 'Deep learning', 'WebRTC', 'Python ML stack', 'Security concepts', 'Real-time systems'],
    tags: ['AI', 'Computer Vision', 'Education', 'Python', 'TensorFlow'],
    createdAt: new Date('2024-01-17')
  },
  {
    id: 'fallback-18',
    slug: 'supply-chain-tracker',
    title: 'Supply Chain Management & Tracking System',
    description: 'End-to-end supply chain visibility with IoT integration and predictive analytics',
    longDescription: 'Create a comprehensive supply chain management system that provides real-time tracking of goods, inventory optimization, demand forecasting, supplier management, and logistics coordination. Integrates with IoT sensors for temperature, location, and condition monitoring.',
    domain: 'WEB_DEVELOPMENT',
    difficulty: 'ADVANCED',
    estimatedHours: 450,
    techStack: ['Java', 'Spring Boot', 'Angular', 'PostgreSQL', 'Apache Kafka', 'Redis', 'MQTT', 'Docker', 'Grafana'],
    features: ['Real-time tracking', 'Inventory management', 'Demand forecasting', 'Supplier portal', 'Route optimization', 'IoT integration', 'Warehouse management', 'Analytics dashboard', 'Alert system', 'Blockchain integration'],
    learningOutcomes: ['Build enterprise systems', 'Implement event-driven architecture', 'Handle IoT data', 'Design complex workflows', 'Optimize logistics', 'Deploy distributed systems'],
    prerequisites: ['Java & Spring Boot', 'Enterprise architecture', 'IoT protocols', 'Supply chain concepts', 'Microservices', 'Message queues'],
    tags: ['Supply Chain', 'Enterprise', 'Java', 'IoT', 'Logistics'],
    createdAt: new Date('2024-01-18')
  },
  {
    id: 'fallback-19',
    slug: 'music-streaming-app',
    title: 'Music Streaming & Discovery Platform',
    description: 'Spotify-like music streaming service with personalized playlists and social features',
    longDescription: 'Build a feature-rich music streaming platform with high-quality audio streaming, personalized recommendations, playlist creation, social sharing, artist profiles, and music discovery features. Implements audio fingerprinting and collaborative filtering for recommendations.',
    domain: 'WEB_DEVELOPMENT',
    difficulty: 'ADVANCED',
    estimatedHours: 420,
    techStack: ['Next.js', 'TypeScript', 'Node.js', 'PostgreSQL', 'Redis', 'Elasticsearch', 'AWS S3', 'Web Audio API', 'Socket.io'],
    features: ['Audio streaming', 'Playlist management', 'Music recommendations', 'Social features', 'Artist profiles', 'Search functionality', 'Offline mode', 'Lyrics display', 'Queue management', 'Cross-device sync'],
    learningOutcomes: ['Implement audio streaming', 'Build recommendation engines', 'Handle large media libraries', 'Design scalable APIs', 'Optimize search', 'Create real-time features'],
    prerequisites: ['Full-stack development', 'Audio processing', 'Recommendation systems', 'Search optimization', 'Cloud storage', 'Real-time sync'],
    tags: ['Music', 'Streaming', 'Next.js', 'Audio', 'Recommendations'],
    createdAt: new Date('2024-01-19')
  },
  {
    id: 'fallback-20',
    slug: 'property-management-system',
    title: 'Real Estate Property Management Platform',
    description: 'Complete property management solution with tenant portal and maintenance tracking',
    longDescription: 'Develop a comprehensive property management system for landlords and property managers featuring tenant portals, rent collection, maintenance requests, lease management, document storage, and financial reporting. Includes mobile apps for tenants and maintenance staff.',
    domain: 'WEB_DEVELOPMENT',
    difficulty: 'INTERMEDIATE',
    estimatedHours: 360,
    techStack: ['React', 'Node.js', 'Express', 'MongoDB', 'Stripe', 'Twilio', 'AWS S3', 'React Native', 'Chart.js'],
    features: ['Tenant portal', 'Rent collection', 'Maintenance tracking', 'Lease management', 'Document storage', 'Payment processing', 'Communication tools', 'Financial reports', 'Mobile apps', 'Notification system'],
    learningOutcomes: ['Build multi-tenant systems', 'Implement payment processing', 'Design document management', 'Create mobile apps', 'Handle financial data', 'Deploy full-stack apps'],
    prerequisites: ['Full-stack JavaScript', 'Payment integration', 'Mobile development', 'Document handling', 'Multi-tenancy', 'Financial systems'],
    tags: ['Real Estate', 'Property Management', 'React', 'Node.js', 'Mobile'],
    createdAt: new Date('2024-01-20')
  },
  {
    id: 'fallback-21',
    slug: 'cybersecurity-monitoring',
    title: 'Network Security Monitoring & Threat Detection',
    description: 'Real-time network monitoring with intrusion detection and threat intelligence',
    longDescription: 'Build a comprehensive cybersecurity monitoring platform that provides real-time network traffic analysis, intrusion detection, vulnerability scanning, threat intelligence integration, and automated incident response. Features machine learning-based anomaly detection and detailed security reports.',
    domain: 'CYBERSECURITY',
    difficulty: 'ADVANCED',
    estimatedHours: 450,
    techStack: ['Python', 'Scapy', 'Snort', 'Elasticsearch', 'Kibana', 'Flask', 'React', 'PostgreSQL', 'Redis', 'Docker'],
    features: ['Network traffic analysis', 'Intrusion detection', 'Vulnerability scanning', 'Threat intelligence', 'Anomaly detection', 'Incident response', 'Log aggregation', 'Alert system', 'Compliance reporting', 'Forensics tools'],
    learningOutcomes: ['Implement security monitoring', 'Build IDS systems', 'Analyze network traffic', 'Detect anomalies', 'Handle security incidents', 'Deploy security tools'],
    prerequisites: ['Network security', 'Python security tools', 'IDS/IPS concepts', 'Threat intelligence', 'Machine learning', 'Security frameworks'],
    tags: ['Cybersecurity', 'Network Security', 'Python', 'Threat Detection', 'IDS'],
    createdAt: new Date('2024-01-21')
  },
  {
    id: 'fallback-22',
    slug: 'learning-management-system',
    title: 'Learning Management System (LMS)',
    description: 'Complete e-learning platform with courses, assessments, and progress tracking',
    longDescription: 'Create a full-featured learning management system for educational institutions with course creation, video lectures, assignments, quizzes, discussion forums, grade management, and analytics. Supports multiple learning paths, certifications, and gamification elements.',
    domain: 'WEB_DEVELOPMENT',
    difficulty: 'INTERMEDIATE',
    estimatedHours: 380,
    techStack: ['Next.js', 'TypeScript', 'Node.js', 'PostgreSQL', 'Redis', 'AWS S3', 'Socket.io', 'Chart.js', 'Stripe'],
    features: ['Course management', 'Video lectures', 'Assignments & quizzes', 'Discussion forums', 'Grade tracking', 'Progress analytics', 'Certificates', 'Gamification', 'Live classes', 'Mobile responsive'],
    learningOutcomes: ['Build educational platforms', 'Implement video delivery', 'Design assessment systems', 'Create analytics dashboards', 'Handle user progress', 'Deploy scalable apps'],
    prerequisites: ['Full-stack development', 'Video streaming', 'Database design', 'Real-time features', 'Payment integration', 'Educational concepts'],
    tags: ['Education', 'E-learning', 'Next.js', 'LMS', 'Video'],
    createdAt: new Date('2024-01-22')
  },
  {
    id: 'fallback-23',
    slug: 'weather-forecasting-system',
    title: 'Advanced Weather Forecasting & Analysis System',
    description: 'ML-based weather prediction with historical data analysis and visualization',
    longDescription: 'Develop a sophisticated weather forecasting system that uses machine learning models to predict weather patterns, analyzes historical data, provides severe weather alerts, and offers detailed visualizations. Integrates with multiple weather APIs and IoT sensors for accurate predictions.',
    domain: 'DATA_SCIENCE',
    difficulty: 'ADVANCED',
    estimatedHours: 380,
    techStack: ['Python', 'TensorFlow', 'Pandas', 'FastAPI', 'React', 'PostgreSQL', 'InfluxDB', 'Plotly', 'Docker'],
    features: ['Weather prediction', 'Historical analysis', 'Severe weather alerts', 'Interactive maps', 'Climate trends', 'API integration', 'IoT sensor data', 'Custom forecasts', 'Mobile notifications', 'Data export'],
    learningOutcomes: ['Build forecasting models', 'Handle time series data', 'Integrate weather APIs', 'Create data visualizations', 'Deploy ML models', 'Design alert systems'],
    prerequisites: ['Machine learning', 'Time series analysis', 'Python data science', 'API integration', 'Data visualization', 'Meteorology basics'],
    tags: ['Weather', 'Machine Learning', 'Python', 'Forecasting', 'Data Science'],
    createdAt: new Date('2024-01-23')
  },
  {
    id: 'fallback-24',
    slug: 'task-automation-platform',
    title: 'No-Code Task Automation Platform',
    description: 'Zapier-like automation platform with visual workflow builder and integrations',
    longDescription: 'Build a no-code automation platform that allows users to create workflows connecting different apps and services. Features a visual workflow builder, pre-built templates, conditional logic, data transformation, and integrations with popular services like Gmail, Slack, Google Sheets, and more.',
    domain: 'WEB_DEVELOPMENT',
    difficulty: 'ADVANCED',
    estimatedHours: 460,
    techStack: ['React', 'Node.js', 'TypeScript', 'MongoDB', 'Redis', 'Bull', 'Docker', 'OAuth2', 'Webhooks'],
    features: ['Visual workflow builder', 'App integrations', 'Conditional logic', 'Data transformation', 'Scheduled tasks', 'Webhook support', 'Template library', 'Error handling', 'Execution logs', 'Team collaboration'],
    learningOutcomes: ['Build workflow engines', 'Implement OAuth integrations', 'Design visual builders', 'Handle async tasks', 'Create plugin systems', 'Deploy automation platforms'],
    prerequisites: ['Full-stack development', 'OAuth & APIs', 'Queue systems', 'Workflow design', 'Integration patterns', 'Async programming'],
    tags: ['Automation', 'No-Code', 'Workflow', 'React', 'Node.js'],
    createdAt: new Date('2024-01-24')
  },
  {
    id: 'fallback-25',
    slug: 'telemedicine-platform',
    title: 'Telemedicine & Virtual Healthcare Platform',
    description: 'Complete telehealth solution with video consultations and prescription management',
    longDescription: 'Create a comprehensive telemedicine platform enabling virtual doctor consultations, appointment scheduling, prescription management, medical records access, and payment processing. Features HIPAA-compliant video calls, chat functionality, and integration with pharmacy systems.',
    domain: 'WEB_DEVELOPMENT',
    difficulty: 'ADVANCED',
    estimatedHours: 440,
    techStack: ['Next.js', 'TypeScript', 'Node.js', 'PostgreSQL', 'WebRTC', 'Twilio', 'Stripe', 'AWS S3', 'Redis'],
    features: ['Video consultations', 'Appointment booking', 'Prescription management', 'Medical records', 'Payment processing', 'Chat functionality', 'Pharmacy integration', 'Insurance verification', 'Notification system', 'Analytics dashboard'],
    learningOutcomes: ['Build healthcare applications', 'Implement video calling', 'Handle sensitive data', 'Design HIPAA compliance', 'Integrate payment systems', 'Deploy secure platforms'],
    prerequisites: ['Full-stack development', 'WebRTC', 'Healthcare regulations', 'Security best practices', 'Payment integration', 'HIPAA compliance'],
    tags: ['Healthcare', 'Telemedicine', 'Next.js', 'WebRTC', 'HIPAA'],
    createdAt: new Date('2024-01-25')
  },
  {
    id: 'fallback-26',
    slug: 'inventory-management-system',
    title: 'Multi-Warehouse Inventory Management System',
    description: 'Enterprise inventory system with barcode scanning and real-time tracking',
    longDescription: 'Develop a robust inventory management system for businesses with multiple warehouses featuring real-time stock tracking, barcode/QR scanning, automated reordering, supplier management, batch tracking, and comprehensive reporting. Includes mobile apps for warehouse staff.',
    domain: 'WEB_DEVELOPMENT',
    difficulty: 'INTERMEDIATE',
    estimatedHours: 340,
    techStack: ['Java', 'Spring Boot', 'React', 'PostgreSQL', 'Redis', 'Apache Kafka', 'React Native', 'Docker'],
    features: ['Stock tracking', 'Barcode scanning', 'Multi-warehouse', 'Automated reordering', 'Supplier management', 'Batch tracking', 'Transfer orders', 'Mobile apps', 'Reports & analytics', 'API integration'],
    learningOutcomes: ['Build inventory systems', 'Implement barcode scanning', 'Design multi-location logic', 'Handle stock movements', 'Create mobile apps', 'Deploy enterprise apps'],
    prerequisites: ['Java & Spring Boot', 'Database design', 'Mobile development', 'Inventory concepts', 'API development', 'Enterprise patterns'],
    tags: ['Inventory', 'Enterprise', 'Java', 'Spring Boot', 'Mobile'],
    createdAt: new Date('2024-01-26')
  },
  {
    id: 'fallback-27',
    slug: 'fraud-detection-system',
    title: 'Real-Time Fraud Detection System',
    description: 'ML-based fraud detection for financial transactions with anomaly detection',
    longDescription: 'Build an intelligent fraud detection system that analyzes financial transactions in real-time using machine learning algorithms, behavioral analysis, and rule-based engines. Features anomaly detection, risk scoring, case management, and automated alerts for suspicious activities.',
    domain: 'MACHINE_LEARNING',
    difficulty: 'ADVANCED',
    estimatedHours: 420,
    techStack: ['Python', 'scikit-learn', 'XGBoost', 'FastAPI', 'React', 'PostgreSQL', 'Redis', 'Apache Kafka', 'Elasticsearch'],
    features: ['Real-time analysis', 'Anomaly detection', 'Risk scoring', 'Rule engine', 'Case management', 'Alert system', 'Pattern recognition', 'Behavioral analysis', 'Reporting dashboard', 'Model monitoring'],
    learningOutcomes: ['Build fraud detection systems', 'Implement ML classifiers', 'Handle imbalanced data', 'Design real-time pipelines', 'Create rule engines', 'Deploy ML in production'],
    prerequisites: ['Machine learning', 'Python ML stack', 'Fraud detection concepts', 'Real-time systems', 'Feature engineering', 'Model deployment'],
    tags: ['Fraud Detection', 'Machine Learning', 'Python', 'Real-time', 'Security'],
    createdAt: new Date('2024-01-27')
  },
  {
    id: 'fallback-28',
    slug: 'job-portal-platform',
    title: 'Job Portal & Recruitment Platform',
    description: 'Complete job marketplace with AI-powered matching and applicant tracking',
    longDescription: 'Create a comprehensive job portal connecting employers and job seekers with AI-powered job matching, resume parsing, applicant tracking system (ATS), video interviews, skill assessments, and analytics. Features company profiles, job alerts, and application management.',
    domain: 'WEB_DEVELOPMENT',
    difficulty: 'INTERMEDIATE',
    estimatedHours: 360,
    techStack: ['Next.js', 'TypeScript', 'Node.js', 'MongoDB', 'Elasticsearch', 'Redis', 'AWS S3', 'Socket.io', 'Stripe'],
    features: ['Job posting', 'Resume parsing', 'AI matching', 'Applicant tracking', 'Video interviews', 'Skill assessments', 'Company profiles', 'Job alerts', 'Application management', 'Analytics dashboard'],
    learningOutcomes: ['Build marketplace platforms', 'Implement search functionality', 'Design matching algorithms', 'Handle file processing', 'Create notification systems', 'Deploy scalable apps'],
    prerequisites: ['Full-stack development', 'Search optimization', 'NLP basics', 'Payment integration', 'Real-time features', 'Recruitment concepts'],
    tags: ['Job Portal', 'Recruitment', 'Next.js', 'AI Matching', 'ATS'],
    createdAt: new Date('2024-01-28')
  },
  {
    id: 'fallback-29',
    slug: 'smart-parking-system',
    title: 'IoT-Based Smart Parking Management System',
    description: 'Automated parking solution with real-time availability and mobile payments',
    longDescription: 'Develop a smart parking management system using IoT sensors to detect parking space availability in real-time. Features mobile app for finding spots, automated payment processing, reservation system, license plate recognition, and analytics for parking operators.',
    domain: 'IOT',
    difficulty: 'ADVANCED',
    estimatedHours: 400,
    techStack: ['Python', 'Flask', 'React Native', 'MQTT', 'PostgreSQL', 'Redis', 'OpenCV', 'Raspberry Pi', 'Stripe'],
    features: ['Real-time availability', 'Space detection', 'Mobile booking', 'Payment processing', 'License plate recognition', 'Navigation guidance', 'Reservation system', 'Analytics dashboard', 'Violation detection', 'Revenue management'],
    learningOutcomes: ['Build IoT systems', 'Implement computer vision', 'Handle sensor data', 'Design mobile apps', 'Create payment systems', 'Deploy edge computing'],
    prerequisites: ['IoT protocols', 'Computer vision', 'Mobile development', 'MQTT messaging', 'Payment integration', 'Embedded systems'],
    tags: ['IoT', 'Smart City', 'Computer Vision', 'Python', 'Mobile'],
    createdAt: new Date('2024-01-29')
  },
  {
    id: 'fallback-30',
    slug: 'content-management-system',
    title: 'Headless CMS with Multi-Channel Publishing',
    description: 'Modern headless CMS with API-first approach and multi-platform content delivery',
    longDescription: 'Build a powerful headless content management system that provides an API-first approach for managing and delivering content across multiple platforms (web, mobile, IoT). Features a visual editor, content versioning, workflow management, media library, and GraphQL/REST APIs.',
    domain: 'WEB_DEVELOPMENT',
    difficulty: 'ADVANCED',
    estimatedHours: 440,
    techStack: ['Next.js', 'TypeScript', 'Node.js', 'GraphQL', 'MongoDB', 'Redis', 'Elasticsearch', 'AWS S3', 'Docker'],
    features: ['Visual editor', 'Content modeling', 'Version control', 'Workflow management', 'Media library', 'GraphQL API', 'REST API', 'Multi-language', 'Role-based access', 'Webhooks'],
    learningOutcomes: ['Build headless CMS', 'Implement GraphQL', 'Design content models', 'Create visual editors', 'Handle versioning', 'Deploy API platforms'],
    prerequisites: ['Full-stack development', 'GraphQL', 'Content management', 'API design', 'Database modeling', 'Cloud storage'],
    tags: ['CMS', 'Headless', 'GraphQL', 'Next.js', 'API'],
    createdAt: new Date('2024-01-30')
  }
];
